package sporeaoc.byg.byglists;

import net.minecraft.world.biome.Biome;
import sporeaoc.byg.biomes.beachbiomes.SnowyBlackBeach;
import sporeaoc.byg.biomes.beachbiomes.SnowyRockyBlackBeach;
import sporeaoc.byg.biomes.beachbiomes.WhiteBeach;
import sporeaoc.byg.biomes.bygamplifiedbiomes.*;
import sporeaoc.byg.biomes.bygbiomes.*;

public class BYGBiomeList {

    public static Biome ALLIUMFIELDS = new AlliumFields();
    public static Biome ALPS = new Alps();
    public static Biome AMARANTHFIELDS = new AmaranthFields();
    public static Biome ANCIENTFOREST = new AncientForest();
    public static Biome ASPENFOREST = new AspenForest();
    public static Biome BAOBABSAVANNA = new BaobabSavanna();
    public static Biome BAYOU = new Bayou();
    public static Biome BLUEGIANTTAIGA = new BlueGiantTaiga();
    public static Biome BLUETAIGA = new BlueTaiga();
    public static Biome BLUFFMOUNTAINS = new BluffMountains();
    public static Biome BOG = new Bog();
    public static Biome BOREALFOREST = new BorealForest();
    public static Biome CANYONS = new Canyons();
    public static Biome CHAPPARALCOASTALS = new ChapparalCoastals();
    public static Biome CHERRYBLOSSOMFOREST = new CherryBlossomForest();
    public static Biome COASTALREDWOODTROPICS = new CoastalRedwoodTropics();
    public static Biome CONIFEROUSFOREST = new ConiferousForest();
    public static Biome DEADSEA = new DeadSea();
    public static Biome DECIDUOUSFOREST = new DeciduousForest();
    public static Biome DOVERMOUNTAINS = new DoverMountains();
    public static Biome DUNES = new Dunes();
    public static Biome EBONYWOODS = new EbonyWoods();
    public static Biome ENCHANTEDFOREST = new EnchantedForest();
    public static Biome EVERGREENTAIGA = new EvergreenTaiga();
    public static Biome FLOWERINGPLAINS = new FloweringPlains();
    public static Biome GLOWSHROOMBAYOU = new GlowShroomBayou();
    public static Biome GRASSLANDPLATEAU = new GrassLandPlateau();
    public static Biome GREATLAKES = new GreatLakes();
    public static Biome GUIANASHIELD = new GuianaShield();
    public static Biome JACARANDAFOREST = new JacarandaForest();
    public static Biome MANGROVEMARSHES = new MangroveMarshes();
    public static Biome MAPLETAIGA = new MapleTaiga();
    public static Biome MARSHLANDS = new MarshLands();
    public static Biome MEADOW = new Meadow();
    public static Biome ORCHARD = new Orchard();
    public static Biome PINELOWANDS = new PineLowlands();
    public static Biome PINEMOUNTAINS = new PineMountains();
    public static Biome PRAIRIE = new Prairie();
    public static Biome QUAGMIRE = new Quagmire();
    public static Biome REDDESERT = new RedDesert();
    public static Biome REDDESERTDUNES = new RedDesertDunes();
    public static Biome REDOAKFOREST = new RedOakForest();
    public static Biome SAVANNACANOPY = new SavannaCanopy();
    public static Biome SEASONALBIRCHFOREST = new SeasonalBirchForest();
    public static Biome SEASONALDECIDUOUSFOREST = new SeasonalDeciduousForest();
    public static Biome SEASONALFOREST = new SeasonalForest();
    public static Biome SEASONALGIANTTAIGA = new SeasonalGiantTaiga();
    public static Biome SEASONALTAIGA = new SeasonalTaiga();
    public static Biome SHRUBLANDS = new ShrubLands();
    public static Biome SKYRISHIGHLANDS = new SkyrisHighlands();
    public static Biome SNOWYBLUEGIANTTAIGA = new SnowyBlueGiantTaiga();
    public static Biome SNOWYBLUETAIGA = new SnowyBlueTaiga();
    public static Biome SNOWYCONIFEROUSFOREST = new SnowyConiferousForest();
    public static Biome SNOWYDECIDUOUSFOREST = new SnowyDeciduousForest();
    public static Biome SNOWYEVERGREENTAIGA = new SnowyEvergreenTaiga();
    public static Biome SNOWYPINEMOUNTAINS = new SnowyPineMountains();
    public static Biome SONORANDESERT = new SonoranDesert();
    public static Biome STONEBRUSHLANDS = new StoneBrushlands();
    public static Biome TROPICALFUNGALRAINFOREST = new TropicalFungalRainForest();
    public static Biome TROPICALISLANDS = new TropicalIslands();
    public static Biome TROPICALRAINFOREST = new TropicalRainForest();
    public static Biome WEEPINGWITCHFOREST = new WeepingWitchForest();
    public static Biome WOODLANDS = new WoodLands();
    public static Biome ZELKOVAFOREST = new ZelkovaForest();

    //Amplified Biomes
    public static Biome aASPENFOREST = new AmplifiedAspenForest();
    public static Biome aBAOBABSAVANNA = new AmplifiedBaobabSavanna();
    public static Biome aBLUEGIANTAIGA = new AmplifiedBlueGiantTaiga();
    public static Biome aBLUETAIGA = new AmplifiedBlueTaiga();
    public static Biome aBLUFFMOUNTAINS = new AmplifiedBluffMountains();
    public static Biome aBOREALFOREST = new AmplifiedBorealForest();
    public static Biome aCHAPPARALCOASTALS = new AmplifiedChapparalCoastals();
    public static Biome aCHERRYBLOSSOMFOREST = new AmplifiedCherryBlossomForest();
    public static Biome aCONIFEROUSFOREST = new AmplifiedConiferousForest();
    public static Biome aDECIDUOUSFOREST = new AmplifiedDeciduousForest();
    public static Biome aDOVERMOUNTAINS = new AmplifiedDoverMountains();
    public static Biome aEBONYWOODS = new AmplifiedEbonyWoods();
    public static Biome aENCHANTEDFOREST = new AmplifiedEnchantedForest();
    public static Biome aEVERGREENTAIGA = new AmplifiedEvergreenTaiga();
    public static Biome aJACARANDAFOREST = new AmplifiedJacarandaForest();
    public static Biome aMAPLETAIGA = new AmplifiedMapleTaiga();
    public static Biome aORCHARD = new AmplifiedOrchard();
    public static Biome aPINEMOUNTAINS = new AmplifiedPineMountains();
    public static Biome aREDDESERTDUNES = new AmplifiedRedDesertDunes();
    public static Biome aREDOAKFOREST = new AmplifiedRedOakForest();
    public static Biome aSAVANNACANOPY = new AmplifiedSavannaCanopy();
    public static Biome aSEASONALBIRCHFOREST = new AmplifiedSeasonalBirchForest();
    public static Biome aSEASONALDECIDUOUSFOREST = new AmplifiedSeasonalDeciduousForest();
    public static Biome aSEASONALFOREST = new AmplifiedSeasonalForest();
    public static Biome aSEASONALGIANTTAIGA = new AmplifiedSeasonalGiantTaiga();
    public static Biome aSEASONALTAIGA = new AmplifiedSeasonalTaiga();
    public static Biome aSHRUBLANDS = new AmplifiedShrubLands();
    public static Biome aSKYRISHIGHLANDS = new AmplifiedSkyrisHighlands();
    public static Biome aSNOWYBLUEGIANTTAIGA = new AmplifiedSnowyBlueGiantTaiga();
    public static Biome aSNOWYCONIFEROUSFOREST = new AmplifiedSnowyConiferousForest();
    public static Biome aSNOWYDECIDUOUSFOREST = new AmplifiedSnowyDeciduousForest();
    public static Biome aSNOWYEVERGREENFOREST = new AmplifiedSnowyEvergreenTaiga();
    public static Biome aSNOWYPINEMOUNTAINS = new AmplifiedSnowyPineMountains();
    public static Biome aSONORANDESERT = new AmplifiedSonoranDesert();
    public static Biome aSTONEBRUSHLANDS = new AmplifiedStoneBrushlands();
    public static Biome aTROPICALFINGALRAINFOREST = new AmplifiedTropicalFungalRainForest();
    public static Biome aTROPICALRAINFOREST = new AmplifiedTropicalRainForest();
    public static Biome aWEEPINGWITCHFOREST = new AmplifiedWeepingWitchForest();
    public static Biome aWOODLANDS = new AmplifiedWoodLands();
    public static Biome aZELKOVAFOREST = new AmplifiedZelkovaForest();

    public static Biome SNOWYROCKYBLACKBEACH = new SnowyRockyBlackBeach();
    public static Biome SNOWYBLACKBEACH = new SnowyBlackBeach();

    public static Biome WHITEBEACH = new WhiteBeach();
    public static Biome DEEPCOOLOCEAN = new DeepCoolOcean();

}
