package sporeaoc.byg.items;

import net.minecraft.item.Item;

public class FlowerItems {
    public static Item ALPINE_BELLFLOWER;
    public static Item ALLIUM_FLOWER_BUSH;
    public static Item PINK_ALLIUM_FLOWER_BUSH;
    public static Item ANGELICA;
    public static Item AZALEA;
    public static Item BEGONIA;
    public static Item BISTORT;
    public static Item BLACK_ROSE;
    public static Item BLUE_SAGE;
    public static Item CALIFORNIA_POPPY;
    public static Item CROCUS;
    public static Item CYAN_ROSE;
    public static Item CYAN_TULIP;
    public static Item DAFFODIL;
    public static Item DELPHINIUM;
    public static Item FAIRY_SLIPPER;
    public static Item FIRECRACKER_FLOWER_BUSH;
    public static Item FOXGLOVE;
    public static Item GOLDEN_SPINED_CACTUS;
    public static Item GREEN_TULIP;
    public static Item GUZMANIA;
    public static Item INCAN_LILY;
    public static Item IRIS;
    public static Item JAPANESE_ORCHID;
    public static Item KOVAN_FLOWER;
    public static Item LAZARUS_BELLFLOWER;
    public static Item LOLIPOP_FLOWER;
    public static Item MAGENTA_TULIP;
    public static Item ORANGE_DAISY;
    public static Item ORSIRIA_ROSE;
    public static Item PEACH_LEATHER_FLOWER;
    public static Item PINK_ALLIUM;
    public static Item PINK_ANEMONE;
    public static Item PINK_DAFFODIL;
    public static Item PINK_ORCHID;
    public static Item PROTEA_FLOWER;
    public static Item PURPLE_ORCHID;
    public static Item PURPLE_SAGE;
    public static Item PURPLE_TULIP;
    public static Item RED_CORNFLOWER;
    public static Item RED_ORCHID;
    public static Item RICHEA;
    public static Item ROSE;
    public static Item SILVER_VASE_FLOWER;
    public static Item SNOWDROPS;
    public static Item TORCH_GINGER;
    public static Item VIOLET_LEATHER_FLOWER;
    public static Item WHITE_ANEMONE;
    public static Item WHITE_SAGE;
    public static Item WINTER_CYCLAMEN;
    public static Item WINTER_ROSE;
    public static Item WINTER_SCILLA;
    public static Item YELLOW_DAFFODIL;
    public static Item YELLOW_TULIP;
    public static Item AMARANTH;
    public static Item CYAN_AMARANTH;
    public static Item ORANGE_AMARANTH;
    public static Item MAGENTA_AMARANTH;
    public static Item PURPLE_AMARANTH;

}
