package sporeaoc.byg.registries;

import net.minecraft.item.*;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import sporeaoc.byg.BYG;
import sporeaoc.byg.byglists.BYGBlockList;
import sporeaoc.byg.byglists.BYGItemList;
import sporeaoc.byg.itemtiers.BYGItemTiers;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class BYGItemRegistry {

    @SubscribeEvent
    public static void bygRegisterItems(RegistryEvent.Register<Item> event) {
        event.getRegistry().registerAll(
                BYGItemList.AMETRINE_AXE = new AxeItem(BYGItemTiers.AMETRINE, 3, -2.4F, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_axe"),
                BYGItemList.AMETRINE_PICK = new PickaxeItem(BYGItemTiers.AMETRINE, 3, -2.4F, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_pickaxe"),
                BYGItemList.AMETRINE_SWORD = new SwordItem(BYGItemTiers.AMETRINE, 3, -2.4F, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_sword"),
                BYGItemList.AMETRINE_BATTLEAXE = new AxeItem(BYGItemTiers.AMETRINE, 3, -2.4F, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_battleaxe"),
                //BYGItemList.AMETRINE_HOE = new HoeItem(BYGItemTiers.AMETRINE, 3, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_hoe"),

                //BYGItemList.AMETRINE_HELMET = new ArmorItem(BYGArmorTiers.AMETRINE, EquipmentSlotType.HEAD, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_helmet"),
                //BYGItemList.AMETRINE_CHEST = new ArmorItem(BYGArmorTiers.AMETRINE, EquipmentSlotType.CHEST, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_chestplate"),
                //BYGItemList.AMETRINE_LEGGINGS = new ArmorItem(BYGArmorTiers.AMETRINE, EquipmentSlotType.LEGS, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_leggings"),
                //BYGItemList.AMETRINE_BOOTS = new ArmorItem(BYGArmorTiers.AMETRINE, EquipmentSlotType.FEET, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("ametrine_boots"),
                //BYGItemList.AMETRINE_SHIELD = new ShieldItem(new Item.Properties().maxDamage(1000).group(ItemGroup.COMBAT)).setRegistryName("ametrine_blue_shields"),

                BYGItemList.PENDORITE_AXE = new AxeItem(BYGItemTiers.PENDORITE, 6.0f, -3.0F, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_axe"),
                BYGItemList.PENDORITE_PICK = new PickaxeItem(BYGItemTiers.PENDORITE, 2, -2.8F, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_pickaxe"),
                BYGItemList.PENDORITE_SWORD = new SwordItem(BYGItemTiers.PENDORITE, 4, -2.4F, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_sword"),
                BYGItemList.PENDORITE_BATTLEAXE = new AxeItem(BYGItemTiers.PENDORITE, 9.0f, -3.3F, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_battleaxe"),
                //BYGItemList.PENDORITE_HOE = new HoeItem(BYGItemTiers.PENDORITE, 0.5f, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_hoe"),

                //BYGItemList.PENDORITE_HELMET = new ArmorItem(BYGArmorTiers.PENDORITE, EquipmentSlotType.HEAD, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_helmet"),
                //BYGItemList.PENDORITE_CHEST = new ArmorItem(BYGArmorTiers.PENDORITE, EquipmentSlotType.CHEST, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_chestplate"),
                //BYGItemList.PENDORITE_LEGGINGS = new ArmorItem(BYGArmorTiers.PENDORITE, EquipmentSlotType.LEGS, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_leggings"),
                //BYGItemList.PENDORITE_BOOTS = new ArmorItem(BYGArmorTiers.PENDORITE, EquipmentSlotType.FEET, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName("pendorite_boots"),
                //BYGItemList.PENDORITE_SHIELD = new ShieldItem(new Item.Properties().maxDamage(1000).group(ItemGroup.COMBAT)).setRegistryName("pendorite_shield"),
                BYGItemList.BYG_LOGO = new Item((new Item.Properties())).setRegistryName("byg_logo"),
                BYGItemList.AMETRINE_GEMS = new Item(new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("ametrine_gems"),
                BYGItemList.PENDORITE_SCRAPS = new Item(new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("pendorite_scraps"),
                BYGItemList.BLUE_BERRY = new BlockNamedItem(BYGBlockList.BLUEBERRY_BUSH, new Item.Properties().group(BYG.Init.creativeTab).food(new Food.Builder().hunger(2).saturation(0.1f).build())).setRegistryName("blueberries"),
                BYGItemList.HOLLY_BERRY = new Item(new Item.Properties().group(BYG.Init.creativeTab).food(new Food.Builder().hunger(2).saturation(0.1f).build())).setRegistryName("holly_berries"),
                BYGItemList.GREEN_APPLE = new Item(new Item.Properties().group(BYG.Init.creativeTab).food(new Food.Builder().hunger(2).saturation(0.1f).build())).setRegistryName("green_apple"),

                BYGItemList.BLUE_GLOWCANE_STALK = new BlockNamedItem(BYGBlockList.BLUE_GLOWCANE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("blue_glowcane_stalk"),
                BYGItemList.RED_GLOWCANE_STALK = new BlockNamedItem(BYGBlockList.RED_GLOWCANE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("red_glowcane_stalk"),
                BYGItemList.PINK_GLOWCANE_STALK = new BlockNamedItem(BYGBlockList.PINK_GLOWCANE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("pink_glowcane_stalk"),
                BYGItemList.PURPLE_GLOWCANE_STALK = new BlockNamedItem(BYGBlockList.PURPLE_GLOWCANE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("purple_glowcane_stalk"),

                BYGItemList.BLUE_GLOWCANE_DUST = new Item(new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("blue_glowcane_dust"),
                BYGItemList.RED_GLOWCANE_DUST = new Item(new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("red_glowcane_dust"),
                BYGItemList.PINK_GLOWCANE_DUST = new Item(new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("pink_glowcane_dust"),
                BYGItemList.PURPLE_GLOWCANE_DUST = new Item(new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("purple_glowcane_dust"),


                //PlankItems
                BYGItemList.ASPEN_PLANKS = new BlockItem(BYGBlockList.ASPEN_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ASPEN_PLANKS.getRegistryName()),
                BYGItemList.BAOBAB_PLANKS = new BlockItem(BYGBlockList.BAOBAB_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BAOBAB_PLANKS.getRegistryName()),
                BYGItemList.BLUE_ENCHANTED_PLANKS = new BlockItem(BYGBlockList.BLUE_ENCHANTED_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_ENCHANTED_PLANKS.getRegistryName()),
                BYGItemList.CHERRY_PLANKS = new BlockItem(BYGBlockList.CHERRY_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CHERRY_PLANKS.getRegistryName()),
                BYGItemList.CIKA_PLANKS = new BlockItem(BYGBlockList.CIKA_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CIKA_PLANKS.getRegistryName()),
                BYGItemList.CYPRESS_PLANKS = new BlockItem(BYGBlockList.CYPRESS_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYPRESS_PLANKS.getRegistryName()),
                BYGItemList.EBONY_PLANKS = new BlockItem(BYGBlockList.EBONY_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.EBONY_PLANKS.getRegistryName()),
                BYGItemList.FIR_PLANKS = new BlockItem(BYGBlockList.FIR_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIR_PLANKS.getRegistryName()),
                BYGItemList.GREEN_ENCHANTED_PLANKS = new BlockItem(BYGBlockList.GREEN_ENCHANTED_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_ENCHANTED_PLANKS.getRegistryName()),
                BYGItemList.HOLLY_PLANKS = new BlockItem(BYGBlockList.HOLLY_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_PLANKS.getRegistryName()),
                BYGItemList.JACARANDA_PLANKS = new BlockItem(BYGBlockList.JACARANDA_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JACARANDA_PLANKS.getRegistryName()),
                BYGItemList.MAHOGANY_PLANKS = new BlockItem(BYGBlockList.MAHOGANY_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAHOGANY_PLANKS.getRegistryName()),
                BYGItemList.MANGROVE_PLANKS = new BlockItem(BYGBlockList.MANGROVE_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MANGROVE_PLANKS.getRegistryName()),
                BYGItemList.MAPLE_PLANKS = new BlockItem(BYGBlockList.MAPLE_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAPLE_PLANKS.getRegistryName()),
                BYGItemList.PINE_PLANKS = new BlockItem(BYGBlockList.PINE_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINE_PLANKS.getRegistryName()),
                BYGItemList.RAINBOW_EUCALYPTUS_PLANKS = new BlockItem(BYGBlockList.RAINBOW_EUCALYPTUS_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RAINBOW_EUCALYPTUS_PLANKS.getRegistryName()),
                BYGItemList.REDWOOD_PLANKS = new BlockItem(BYGBlockList.REDWOOD_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REDWOOD_PLANKS.getRegistryName()),
                BYGItemList.SKYRIS_PLANKS = new BlockItem(BYGBlockList.SKYRIS_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_PLANKS.getRegistryName()),
                BYGItemList.WILLOW_PLANKS = new BlockItem(BYGBlockList.WILLOW_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WILLOW_PLANKS.getRegistryName()),
                BYGItemList.WITCH_HAZEL_PLANKS = new BlockItem(BYGBlockList.WITCH_HAZEL_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WITCH_HAZEL_PLANKS.getRegistryName()),
                BYGItemList.ZELKOVA_PLANKS = new BlockItem(BYGBlockList.ZELKOVA_PLANKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ZELKOVA_PLANKS.getRegistryName()),

                //Bookshelf
                BYGItemList.ASPEN_BOOKSHELF = new BlockItem(BYGBlockList.ASPEN_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ASPEN_BOOKSHELF.getRegistryName()),
                BYGItemList.BAOBAB_BOOKSHELF = new BlockItem(BYGBlockList.BAOBAB_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BAOBAB_BOOKSHELF.getRegistryName()),
                BYGItemList.BLUE_ENCHANTED_BOOKSHELF = new BlockItem(BYGBlockList.BLUE_ENCHANTED_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_ENCHANTED_BOOKSHELF.getRegistryName()),
                BYGItemList.CHERRY_BOOKSHELF = new BlockItem(BYGBlockList.CHERRY_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CHERRY_BOOKSHELF.getRegistryName()),
                BYGItemList.CIKA_BOOKSHELF = new BlockItem(BYGBlockList.CIKA_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CIKA_BOOKSHELF.getRegistryName()),
                BYGItemList.CYPRESS_BOOKSHELF = new BlockItem(BYGBlockList.CYPRESS_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYPRESS_BOOKSHELF.getRegistryName()),
                BYGItemList.EBONY_BOOKSHELF = new BlockItem(BYGBlockList.EBONY_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.EBONY_BOOKSHELF.getRegistryName()),
                BYGItemList.FIR_BOOKSHELF = new BlockItem(BYGBlockList.FIR_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIR_BOOKSHELF.getRegistryName()),
                BYGItemList.GREEN_ENCHANTED_BOOKSHELF = new BlockItem(BYGBlockList.GREEN_ENCHANTED_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_ENCHANTED_BOOKSHELF.getRegistryName()),
                BYGItemList.HOLLY_BOOKSHELF = new BlockItem(BYGBlockList.HOLLY_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_BOOKSHELF.getRegistryName()),
                BYGItemList.JACARANDA_BOOKSHELF = new BlockItem(BYGBlockList.JACARANDA_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JACARANDA_BOOKSHELF.getRegistryName()),
                BYGItemList.MAHOGANY_BOOKSHELF = new BlockItem(BYGBlockList.MAHOGANY_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAHOGANY_BOOKSHELF.getRegistryName()),
                BYGItemList.MANGROVE_BOOKSHELF = new BlockItem(BYGBlockList.MANGROVE_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MANGROVE_BOOKSHELF.getRegistryName()),
                BYGItemList.MAPLE_BOOKSHELF = new BlockItem(BYGBlockList.MAPLE_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAPLE_BOOKSHELF.getRegistryName()),
                BYGItemList.PINE_BOOKSHELF = new BlockItem(BYGBlockList.PINE_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINE_BOOKSHELF.getRegistryName()),
                BYGItemList.RAINBOW_EUCALYPTUS_BOOKSHELF = new BlockItem(BYGBlockList.RAINBOW_EUCALYPTUS_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RAINBOW_EUCALYPTUS_BOOKSHELF.getRegistryName()),
                BYGItemList.REDWOOD_BOOKSHELF = new BlockItem(BYGBlockList.REDWOOD_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REDWOOD_BOOKSHELF.getRegistryName()),
                BYGItemList.SKYRIS_BOOKSHELF = new BlockItem(BYGBlockList.SKYRIS_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_BOOKSHELF.getRegistryName()),
                BYGItemList.WILLOW_BOOKSHELF = new BlockItem(BYGBlockList.WILLOW_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WILLOW_BOOKSHELF.getRegistryName()),
                BYGItemList.WITCH_HAZEL_BOOKSHELF = new BlockItem(BYGBlockList.WITCH_HAZEL_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WITCH_HAZEL_BOOKSHELF.getRegistryName()),
                BYGItemList.ZELKOVA_BOOKSHELF = new BlockItem(BYGBlockList.ZELKOVA_BOOKSHELF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ZELKOVA_BOOKSHELF.getRegistryName()),

                //Slabs
                BYGItemList.ASPEN_SLAB = new BlockItem(BYGBlockList.ASPEN_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ASPEN_SLAB.getRegistryName()),
                BYGItemList.BAOBAB_SLAB = new BlockItem(BYGBlockList.BAOBAB_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BAOBAB_SLAB.getRegistryName()),
                BYGItemList.BLUE_ENCHANTED_SLAB = new BlockItem(BYGBlockList.BLUE_ENCHANTED_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_ENCHANTED_SLAB.getRegistryName()),
                BYGItemList.CHERRY_SLAB = new BlockItem(BYGBlockList.CHERRY_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CHERRY_SLAB.getRegistryName()),
                BYGItemList.CIKA_SLAB = new BlockItem(BYGBlockList.CIKA_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CIKA_SLAB.getRegistryName()),
                BYGItemList.CYPRESS_SLAB = new BlockItem(BYGBlockList.CYPRESS_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYPRESS_SLAB.getRegistryName()),
                BYGItemList.EBONY_SLAB = new BlockItem(BYGBlockList.EBONY_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.EBONY_SLAB.getRegistryName()),
                BYGItemList.FIR_SLAB = new BlockItem(BYGBlockList.FIR_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIR_SLAB.getRegistryName()),
                BYGItemList.GREEN_ENCHANTED_SLAB = new BlockItem(BYGBlockList.GREEN_ENCHANTED_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_ENCHANTED_SLAB.getRegistryName()),
                BYGItemList.HOLLY_SLAB = new BlockItem(BYGBlockList.HOLLY_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_SLAB.getRegistryName()),
                BYGItemList.JACARANDA_SLAB = new BlockItem(BYGBlockList.JACARANDA_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JACARANDA_SLAB.getRegistryName()),
                BYGItemList.MAHOGANY_SLAB = new BlockItem(BYGBlockList.MAHOGANY_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAHOGANY_SLAB.getRegistryName()),
                BYGItemList.MANGROVE_SLAB = new BlockItem(BYGBlockList.MANGROVE_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MANGROVE_SLAB.getRegistryName()),
                BYGItemList.MAPLE_SLAB = new BlockItem(BYGBlockList.MAPLE_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAPLE_SLAB.getRegistryName()),
                BYGItemList.PINE_SLAB = new BlockItem(BYGBlockList.PINE_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINE_SLAB.getRegistryName()),
                BYGItemList.RAINBOW_EUCALYPTUS_SLAB = new BlockItem(BYGBlockList.RAINBOW_EUCALYPTUS_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RAINBOW_EUCALYPTUS_SLAB.getRegistryName()),
                BYGItemList.REDWOOD_SLAB = new BlockItem(BYGBlockList.REDWOOD_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REDWOOD_SLAB.getRegistryName()),
                BYGItemList.SKYRIS_SLAB = new BlockItem(BYGBlockList.SKYRIS_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_SLAB.getRegistryName()),
                BYGItemList.WILLOW_SLAB = new BlockItem(BYGBlockList.WILLOW_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WILLOW_SLAB.getRegistryName()),
                BYGItemList.WITCH_HAZEL_SLAB = new BlockItem(BYGBlockList.WITCH_HAZEL_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WITCH_HAZEL_SLAB.getRegistryName()),
                BYGItemList.ZELKOVA_SLAB = new BlockItem(BYGBlockList.ZELKOVA_SLAB, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ZELKOVA_SLAB.getRegistryName()),

                //Stairs
                BYGItemList.ASPEN_STAIRS = new BlockItem(BYGBlockList.ASPEN_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ASPEN_STAIRS.getRegistryName()),
                BYGItemList.BAOBAB_STAIRS = new BlockItem(BYGBlockList.BAOBAB_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BAOBAB_STAIRS.getRegistryName()),
                BYGItemList.BLUE_ENCHANTED_STAIRS = new BlockItem(BYGBlockList.BLUE_ENCHANTED_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_ENCHANTED_STAIRS.getRegistryName()),
                BYGItemList.CHERRY_STAIRS = new BlockItem(BYGBlockList.CHERRY_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CHERRY_STAIRS.getRegistryName()),
                BYGItemList.CIKA_STAIRS = new BlockItem(BYGBlockList.CIKA_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CIKA_STAIRS.getRegistryName()),
                BYGItemList.CYPRESS_STAIRS = new BlockItem(BYGBlockList.CYPRESS_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYPRESS_STAIRS.getRegistryName()),
                BYGItemList.EBONY_STAIRS = new BlockItem(BYGBlockList.EBONY_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.EBONY_STAIRS.getRegistryName()),
                BYGItemList.FIR_STAIRS = new BlockItem(BYGBlockList.FIR_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIR_STAIRS.getRegistryName()),
                BYGItemList.GREEN_ENCHANTED_STAIRS = new BlockItem(BYGBlockList.GREEN_ENCHANTED_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_ENCHANTED_STAIRS.getRegistryName()),
                BYGItemList.HOLLY_STAIRS = new BlockItem(BYGBlockList.HOLLY_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_STAIRS.getRegistryName()),
                BYGItemList.JACARANDA_STAIRS = new BlockItem(BYGBlockList.JACARANDA_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JACARANDA_STAIRS.getRegistryName()),
                BYGItemList.MAHOGANY_STAIRS = new BlockItem(BYGBlockList.MAHOGANY_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAHOGANY_STAIRS.getRegistryName()),
                BYGItemList.MANGROVE_STAIRS = new BlockItem(BYGBlockList.MANGROVE_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MANGROVE_STAIRS.getRegistryName()),
                BYGItemList.MAPLE_STAIRS = new BlockItem(BYGBlockList.MAPLE_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAPLE_STAIRS.getRegistryName()),
                BYGItemList.PINE_STAIRS = new BlockItem(BYGBlockList.PINE_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINE_STAIRS.getRegistryName()),
                BYGItemList.RAINBOW_EUCALYPTUS_STAIRS = new BlockItem(BYGBlockList.RAINBOW_EUCALYPTUS_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RAINBOW_EUCALYPTUS_STAIRS.getRegistryName()),
                BYGItemList.REDWOOD_STAIRS = new BlockItem(BYGBlockList.REDWOOD_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REDWOOD_STAIRS.getRegistryName()),
                BYGItemList.SKYRIS_STAIRS = new BlockItem(BYGBlockList.SKYRIS_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_STAIRS.getRegistryName()),
                BYGItemList.WILLOW_STAIRS = new BlockItem(BYGBlockList.WILLOW_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WILLOW_STAIRS.getRegistryName()),
                BYGItemList.WITCH_HAZEL_STAIRS = new BlockItem(BYGBlockList.WITCH_HAZEL_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WITCH_HAZEL_STAIRS.getRegistryName()),
                BYGItemList.ZELKOVA_STAIRS = new BlockItem(BYGBlockList.ZELKOVA_STAIRS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ZELKOVA_STAIRS.getRegistryName()),


                //PlantItems
                BYGItemList.GREEN_MUSHROOM_BLOCK = new BlockItem(BYGBlockList.GREEN_MUSHROOM_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_MUSHROOM_BLOCK.getRegistryName()),
                BYGItemList.MILKCAP_MUSHROOM_BLOCK = new BlockItem(BYGBlockList.MILKCAP_MUSHROOM_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MILKCAP_MUSHROOM_BLOCK.getRegistryName()),
                BYGItemList.BLEWIT_MUSHROOM_BLOCK = new BlockItem(BYGBlockList.BLEWIT_MUSHROOM_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLEWIT_MUSHROOM_BLOCK.getRegistryName()),
                BYGItemList.PUFF_MUSHROOM_BLOCK = new BlockItem(BYGBlockList.PUFF_MUSHROOM_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PUFF_MUSHROOM_BLOCK.getRegistryName()),
                BYGItemList.WHITE_MUSHROOM_STEM = new BlockItem(BYGBlockList.WHITE_MUSHROOM_STEM, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WHITE_MUSHROOM_STEM.getRegistryName()),
                BYGItemList.BROWN_MUSHROOM_STEM = new BlockItem(BYGBlockList.BROWN_MUSHROOM_STEM, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BROWN_MUSHROOM_STEM.getRegistryName()),

                BYGItemList.CATTAIL = new BlockItem(BYGBlockList.CATTAIL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CATTAIL.getRegistryName()),
                BYGItemList.REEDS = new BlockItem(BYGBlockList.REEDS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REEDS.getRegistryName()),
                BYGItemList.HORSEWEED = new BlockItem(BYGBlockList.HORSEWEED, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HORSEWEED.getRegistryName()),
                BYGItemList.MINI_CACTUS = new BlockItem(BYGBlockList.MINI_CACTUS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MINI_CACTUS.getRegistryName()),
                BYGItemList.PRICKLY_PEAR_CACTUS = new BlockItem(BYGBlockList.PRICKLY_PEAR_CACTUS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PRICKLY_PEAR_CACTUS.getRegistryName()),
                BYGItemList.WINTER_SUCCULENT = new BlockItem(BYGBlockList.WINTER_SUCCULENT, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WINTER_SUCCULENT.getRegistryName()),
                BYGItemList.SHORT_GRASS = new BlockItem(BYGBlockList.SHORT_GRASS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SHORT_GRASS.getRegistryName()),
                BYGItemList.POISON_IVY = new BlockItem(BYGBlockList.POISON_IVY, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.POISON_IVY.getRegistryName()),
                BYGItemList.TINY_LILYPADS = (new LilyPadItem(BYGBlockList.TINY_LILYPADS, (new Item.Properties()).group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.TINY_LILYPADS.getRegistryName())),

                //Glowcane Blocks
                BYGItemList.RED_GLOWCANE_BLOCK = new BlockItem(BYGBlockList.RED_GLOWCANE_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_GLOWCANE_BLOCK.getRegistryName()),
                BYGItemList.BLUE_GLOWCANE_BLOCK = new BlockItem(BYGBlockList.BLUE_GLOWCANE_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_GLOWCANE_BLOCK.getRegistryName()),
                BYGItemList.PURPLE_GLOWCANE_BLOCK = new BlockItem(BYGBlockList.PURPLE_GLOWCANE_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PURPLE_GLOWCANE_BLOCK.getRegistryName()),
                BYGItemList.PINK_GLOWCANE_BLOCK = new BlockItem(BYGBlockList.PINK_GLOWCANE_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINK_GLOWCANE_BLOCK.getRegistryName()),
//
                //Decorations
                //BYGItemList.REDSTONE_LANTERN = new BlockNamedItem(BYGBlockList.REDSTONE_LANTERN, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName("redstone_lantern"),


                //Petal Blocks
                BYGItemList.WHITE_PETAL = new BlockItem(BYGBlockList.WHITE_PETAL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WHITE_PETAL.getRegistryName()),
                BYGItemList.BLUE_PETAL = new BlockItem(BYGBlockList.BLUE_PETAL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_PETAL.getRegistryName()),
                BYGItemList.LIGHT_BLUE_PETAL = new BlockItem(BYGBlockList.LIGHT_BLUE_PETAL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.LIGHT_BLUE_PETAL.getRegistryName()),
                BYGItemList.PURPLE_PETAL = new BlockItem(BYGBlockList.PURPLE_PETAL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PURPLE_PETAL.getRegistryName()),
                BYGItemList.RED_PETAL = new BlockItem(BYGBlockList.RED_PETAL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_PETAL.getRegistryName()),
                BYGItemList.YELLOW_PETAL = new BlockItem(BYGBlockList.YELLOW_PETAL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.YELLOW_PETAL.getRegistryName()),
                BYGItemList.PLANT_STEM = new BlockItem(BYGBlockList.PLANT_STEM, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PLANT_STEM.getRegistryName()),


                //SaplingItems
                BYGItemList.ASPEN_SAPLING = new BlockItem(BYGBlockList.ASPEN_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ASPEN_SAPLING.getRegistryName()),
                BYGItemList.BAOBAB_SAPLING = new BlockItem(BYGBlockList.BAOBAB_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BAOBAB_SAPLING.getRegistryName()),
                BYGItemList.BLUE_ENCHANTED_SAPLING = new BlockItem(BYGBlockList.BLUE_ENCHANTED_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_ENCHANTED_SAPLING.getRegistryName()),
                BYGItemList.BLUE_SPRUCE_SAPLING = new BlockItem(BYGBlockList.BLUE_SPRUCE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_SPRUCE_SAPLING.getRegistryName()),
                BYGItemList.BROWN_BIRCH_SAPLING = new BlockItem(BYGBlockList.BROWN_BIRCH_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BROWN_BIRCH_SAPLING.getRegistryName()),
                BYGItemList.BROWN_OAK_SAPLING = new BlockItem(BYGBlockList.BROWN_OAK_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BROWN_OAK_SAPLING.getRegistryName()),
                BYGItemList.CIKA_SAPLING = new BlockItem(BYGBlockList.CIKA_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CIKA_SAPLING.getRegistryName()),
                BYGItemList.CYPRESS_SAPLING = new BlockItem(BYGBlockList.CYPRESS_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYPRESS_SAPLING.getRegistryName()),
                BYGItemList.EBONY_SAPLING = new BlockItem(BYGBlockList.EBONY_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.EBONY_SAPLING.getRegistryName()),
                BYGItemList.FIR_SAPLING = new BlockItem(BYGBlockList.FIR_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIR_SAPLING.getRegistryName()),
                BYGItemList.GREEN_ENCHANTED_SAPLING = new BlockItem(BYGBlockList.GREEN_ENCHANTED_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_ENCHANTED_SAPLING.getRegistryName()),
                BYGItemList.HOLLY_SAPLING = new BlockItem(BYGBlockList.HOLLY_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_SAPLING.getRegistryName()),
                BYGItemList.JACARANDA_SAPLING = new BlockItem(BYGBlockList.JACARANDA_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JACARANDA_SAPLING.getRegistryName()),
                BYGItemList.MAHOGONY_SAPLING = new BlockItem(BYGBlockList.MAHOGANY_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAHOGANY_SAPLING.getRegistryName()),
                BYGItemList.MANGROVE_SAPLING = new BlockItem(BYGBlockList.MANGROVE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MANGROVE_SAPLING.getRegistryName()),
                BYGItemList.ORANGE_BIRCH_SAPLING = new BlockItem(BYGBlockList.ORANGE_BIRCH_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORANGE_BIRCH_SAPLING.getRegistryName()),
                BYGItemList.ORANGE_OAK_SAPLING = new BlockItem(BYGBlockList.ORANGE_OAK_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORANGE_OAK_SAPLING.getRegistryName()),
                BYGItemList.ORANGE_SPRUCE_SAPLING = new BlockItem(BYGBlockList.ORANGE_SPRUCE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORANGE_SPRUCE_SAPLING.getRegistryName()),
                BYGItemList.ORCHARD_SAPLING = new BlockItem(BYGBlockList.ORCHARD_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORCHARD_SAPLING.getRegistryName()),
                BYGItemList.PALO_VERDE_SAPLING = new BlockItem(BYGBlockList.PALO_VERDE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PALO_VERDE_SAPLING.getRegistryName()),
                BYGItemList.PINE_SAPLING = new BlockItem(BYGBlockList.PINE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINE_SAPLING.getRegistryName()),
                BYGItemList.PINK_CHERRY_SAPLING = new BlockItem(BYGBlockList.PINK_CHERRY_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINK_CHERRY_SAPLING.getRegistryName()),
                BYGItemList.RAINBOW_EUCALYPTUS_SAPLING = new BlockItem(BYGBlockList.RAINBOW_EUCALYPTUS_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RAINBOW_EUCALYPTUS_SAPLING.getRegistryName()),
                BYGItemList.RED_BIRCH_SAPLING = new BlockItem(BYGBlockList.RED_BIRCH_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_BIRCH_SAPLING.getRegistryName()),
                BYGItemList.RED_MAPLE_SAPLING = new BlockItem(BYGBlockList.RED_MAPLE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_MAPLE_SAPLING.getRegistryName()),
                BYGItemList.RED_OAK_SAPLING = new BlockItem(BYGBlockList.RED_OAK_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_OAK_SAPLING.getRegistryName()),
                BYGItemList.RED_SPRUCE_SAPLINGS = new BlockItem(BYGBlockList.RED_SPRUCE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_SPRUCE_SAPLING.getRegistryName()),
                BYGItemList.REDWOOD_SAPLINGS = new BlockItem(BYGBlockList.REDWOOD_SAPLINGS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REDWOOD_SAPLINGS.getRegistryName()),
                BYGItemList.SILVER_MAPLE_SAPLINGS = new BlockItem(BYGBlockList.SILVER_MAPLE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SILVER_MAPLE_SAPLING.getRegistryName()),
                BYGItemList.SKYRIS_SAPLINGS = new BlockItem(BYGBlockList.SKYRIS_SAPLINGS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_SAPLINGS.getRegistryName()),
                BYGItemList.WHITE_CHERRY_SAPLING = new BlockItem(BYGBlockList.WHITE_CHERRY_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WHITE_CHERRY_SAPLING.getRegistryName()),
                BYGItemList.WILLOW_SAPLING = new BlockItem(BYGBlockList.WILLOW_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WILLOW_SAPLING.getRegistryName()),
                BYGItemList.WITCH_HAZEL_SAPLING = new BlockItem(BYGBlockList.WITCH_HAZEL_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WITCH_HAZEL_SAPLING.getRegistryName()),
                BYGItemList.YELLOW_BIRCH_SAPLING = new BlockItem(BYGBlockList.YELLOW_BIRCH_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.YELLOW_BIRCH_SAPLING.getRegistryName()),
                BYGItemList.YELLOW_SPRUCE_SAPLING = new BlockItem(BYGBlockList.YELLOW_SPRUCE_SAPLING, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.YELLOW_SPRUCE_SAPLING.getRegistryName()),


                //FenceItems
                BYGItemList.ASPEN_FENCE = new BlockItem(BYGBlockList.ASPEN_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ASPEN_FENCE.getRegistryName()),
                BYGItemList.BAOBAB_FENCE = new BlockItem(BYGBlockList.BAOBAB_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BAOBAB_FENCE.getRegistryName()),
                BYGItemList.BLUE_ENCHANTED_FENCE = new BlockItem(BYGBlockList.BLUE_ENCHANTED_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_ENCHANTED_FENCE.getRegistryName()),
                BYGItemList.CHERRY_FENCE = new BlockItem(BYGBlockList.CHERRY_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CHERRY_FENCE.getRegistryName()),
                BYGItemList.CIKA_FENCE = new BlockItem(BYGBlockList.CIKA_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CIKA_FENCE.getRegistryName()),
                BYGItemList.CYPRESS_FENCE = new BlockItem(BYGBlockList.CYPRESS_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYPRESS_FENCE.getRegistryName()),
                BYGItemList.EBONY_FENCE = new BlockItem(BYGBlockList.EBONY_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.EBONY_FENCE.getRegistryName()),
                BYGItemList.FIR_FENCE = new BlockItem(BYGBlockList.FIR_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIR_FENCE.getRegistryName()),
                BYGItemList.GREEN_ENCHANTED_FENCE = new BlockItem(BYGBlockList.GREEN_ENCHANTED_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_ENCHANTED_FENCE.getRegistryName()),
                BYGItemList.HOLLY_FENCE = new BlockItem(BYGBlockList.HOLLY_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_FENCE.getRegistryName()),
                BYGItemList.JACARANDA_FENCE = new BlockItem(BYGBlockList.JACARANDA_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JACARANDA_FENCE.getRegistryName()),
                BYGItemList.MAHOGONY_FENCE = new BlockItem(BYGBlockList.MAHOGONY_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAHOGONY_FENCE.getRegistryName()),
                BYGItemList.MANGROVE_FENCE = new BlockItem(BYGBlockList.MANGROVE_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MANGROVE_FENCE.getRegistryName()),
                BYGItemList.MAPLE_FENCE = new BlockItem(BYGBlockList.MAPLE_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAPLE_FENCE.getRegistryName()),
                BYGItemList.PINE_FENCE = new BlockItem(BYGBlockList.PINE_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINE_FENCE.getRegistryName()),
                BYGItemList.RAINBOW_EUCALYPTUS_FENCE = new BlockItem(BYGBlockList.RAINBOW_EUCALYPTUS_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RAINBOW_EUCALYPTUS_FENCE.getRegistryName()),
                BYGItemList.REDWOOD_FENCE = new BlockItem(BYGBlockList.REDWOOD_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REDWOOD_FENCE.getRegistryName()),
                BYGItemList.SKYRIS_FENCE = new BlockItem(BYGBlockList.SKYRIS_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_FENCE.getRegistryName()),
                BYGItemList.WILLOW_FENCE = new BlockItem(BYGBlockList.WILLOW_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WILLOW_FENCE.getRegistryName()),
                BYGItemList.WITCH_HAZEL_FENCE = new BlockItem(BYGBlockList.WITCH_HAZEL_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WITCH_HAZEL_FENCE.getRegistryName()),
                BYGItemList.ZELKOVA_FENCE = new BlockItem(BYGBlockList.ZELKOVA_FENCE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ZELKOVA_FENCE.getRegistryName()),


                //GrassItems
                BYGItemList.PEAT_GRASSBLOCK = new BlockItem(BYGBlockList.PEAT_GRASSBLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PEAT_GRASSBLOCK.getRegistryName()),
                BYGItemList.MEADOW_GRASSBLOCK = new BlockItem(BYGBlockList.MEADOW_GRASSBLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MEADOW_GRASSBLOCK.getRegistryName()),
                BYGItemList.MEADOW_DIRT = new BlockItem(BYGBlockList.MEADOW_DIRT, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MEADOW_DIRT.getRegistryName()),


                //MushroomItems
                BYGItemList.BLACK_PUFF = new BlockItem(BYGBlockList.BLACK_PUFF, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLACK_PUFF.getRegistryName()),
                BYGItemList.WEEPING_MILKCAP = new BlockItem(BYGBlockList.WEEPING_MILKCAP, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WEEPING_MILKCAP.getRegistryName()),
                BYGItemList.WOOD_BLEWIT = new BlockItem(BYGBlockList.WOOD_BLEWIT, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WOOD_BLEWIT.getRegistryName()),
                BYGItemList.GREEN_MUSHSHROOM = new BlockItem(BYGBlockList.GREEN_MUSHSHROOM, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_MUSHSHROOM.getRegistryName()),


                //OreItems
                BYGItemList.PENDORITE_ORE = new BlockItem(BYGBlockList.PENDORITE_ORE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PENDORITE_ORE.getRegistryName()),
                BYGItemList.AMETRINE_ORE = new BlockItem(BYGBlockList.AMETRINE_ORE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.AMETRINE_ORE.getRegistryName()),
                BYGItemList.PENDORITE_BLOCK = new BlockItem(BYGBlockList.PENDORITE_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PENDORITE_BLOCK.getRegistryName()),
                BYGItemList.AMETRINE_BLOCK = new BlockItem(BYGBlockList.AMETRINE_BLOCK, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.AMETRINE_BLOCK.getRegistryName()),


                //StoneItems
                BYGItemList.DACITE = new BlockItem(BYGBlockList.DACITE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.DACITE.getRegistryName()),
                BYGItemList.DACITE_BRICKS = new BlockItem(BYGBlockList.DACITE_BRICKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.DACITE_BRICKS.getRegistryName()),
                BYGItemList.DACITE_COBBLESTONE = new BlockItem(BYGBlockList.DACITE_COBBLESTONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.DACITE_COBBLESTONE.getRegistryName()),
                BYGItemList.DACITE_PILLAR = new BlockItem(BYGBlockList.DACITE_PILLAR, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.DACITE_PILLAR.getRegistryName()),
                BYGItemList.DACITE_TILE = new BlockItem(BYGBlockList.DACITE_TILE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.DACITE_TILE.getRegistryName()),


                BYGItemList.MOSSY_STONE = new BlockItem(BYGBlockList.MOSSY_STONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MOSSY_STONE.getRegistryName()),
                BYGItemList.OVERGROWN_STONE = new BlockItem(BYGBlockList.OVERGROWN_STONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.OVERGROWN_STONE.getRegistryName()),
                BYGItemList.ROCKY_STONE = new BlockItem(BYGBlockList.ROCKY_STONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ROCKY_STONE.getRegistryName()),


                BYGItemList.SCORIA_STONE = new BlockItem(BYGBlockList.SCORIA_STONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SCORIA_STONE.getRegistryName()),
                BYGItemList.SCORIA_COBBLESTONE = new BlockItem(BYGBlockList.SCORIA_COBBLESTONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SCORIA_COBBLESTONE.getRegistryName()),
                BYGItemList.SCORIA_PILLAR = new BlockItem(BYGBlockList.SCORIA_PILLAR, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SCORIA_PILLAR.getRegistryName()),
                BYGItemList.SCORIA_STONEBRICKS = new BlockItem(BYGBlockList.SCORIA_STONEBRICKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SCORIA_STONEBRICKS.getRegistryName()),


                BYGItemList.SOAPSTONE = new BlockItem(BYGBlockList.SOAPSTONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SOAPSTONE.getRegistryName()),
                BYGItemList.POLISHED_SOAPSTONE = new BlockItem(BYGBlockList.POLISHED_SOAPSTONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.POLISHED_SOAPSTONE.getRegistryName()),
                BYGItemList.SOAPSTONE_BRICKS = new BlockItem(BYGBlockList.SOAPSTONE_BRICKS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SOAPSTONE_BRICKS.getRegistryName()),
                BYGItemList.SOAPSTONE_PILLAR = new BlockItem(BYGBlockList.SOAPSTONE_PILLAR, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SOAPSTONE_PILLAR.getRegistryName()),
                BYGItemList.SOAPSTONE_TILE = new BlockItem(BYGBlockList.SOAPSTONE_TILE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SOAPSTONE_TILE.getRegistryName()),


                //StrippedLogItems
                BYGItemList.STRIPPED_ASPEN_LOG = new BlockItem(BYGBlockList.STRIPPED_ASPEN_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_ASPEN_LOG.getRegistryName()),
                BYGItemList.STRIPPED_BAOBAB_LOG = new BlockItem(BYGBlockList.STRIPPED_BAOBAB_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_BAOBAB_LOG.getRegistryName()),
                BYGItemList.STRIPPED_BLUE_ENCHANTED_LOG = new BlockItem(BYGBlockList.STRIPPED_BLUE_ENCHANTED_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_BLUE_ENCHANTED_LOG.getRegistryName()),
                BYGItemList.STRIPPED_CHERRY_LOG = new BlockItem(BYGBlockList.STRIPPED_CHERRY_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_CHERRY_LOG.getRegistryName()),
                BYGItemList.STRIPPED_CIKA_LOG = new BlockItem(BYGBlockList.STRIPPED_CIKA_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_CIKA_LOG.getRegistryName()),
                BYGItemList.STRIPPED_CYPRESS_LOG = new BlockItem(BYGBlockList.STRIPPED_CYPRESS_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_CYPRESS_LOG.getRegistryName()),
                BYGItemList.STRIPPED_EBONY_LOG = new BlockItem(BYGBlockList.STRIPPED_EBONY_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_EBONY_LOG.getRegistryName()),
                BYGItemList.STRIPPED_FIR_LOG = new BlockItem(BYGBlockList.STRIPPED_FIR_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_FIR_LOG.getRegistryName()),
                BYGItemList.STRIPPED_GREEN_ENCHANTED_LOG = new BlockItem(BYGBlockList.STRIPPED_GREEN_ENCHANTED_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_GREEN_ENCHANTED_LOG.getRegistryName()),
                BYGItemList.STRIPPED_HOLLY_LOG = new BlockItem(BYGBlockList.STRIPPED_HOLLY_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_HOLLY_LOG.getRegistryName()),
                BYGItemList.STRIPPED_JACARANDA_LOG = new BlockItem(BYGBlockList.STRIPPED_JACARANDA_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_JACARANDA_LOG.getRegistryName()),
                BYGItemList.STRIPPED_MAHOGANY_LOG = new BlockItem(BYGBlockList.STRIPPED_MAHOGANY_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_MAHOGANY_LOG.getRegistryName()),
                BYGItemList.STRIPPED_MANGROVE_LOG = new BlockItem(BYGBlockList.STRIPPED_MANGROVE_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_MANGROVE_LOG.getRegistryName()),
                BYGItemList.STRIPPED_MAPLE_LOG = new BlockItem(BYGBlockList.STRIPPED_MAPLE_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_MAPLE_LOG.getRegistryName()),
                BYGItemList.STRIPPED_PALO_VERDE_LOG = new BlockItem(BYGBlockList.STRIPPED_PALO_VERDE_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_PALO_VERDE_LOG.getRegistryName()),
                BYGItemList.STRIPPED_PINE_LOG = new BlockItem(BYGBlockList.STRIPPED_PINE_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_PINE_LOG.getRegistryName()),
                BYGItemList.STRIPPED_RAINBOW_EUCALYPTUS_LOG = new BlockItem(BYGBlockList.STRIPPED_RAINBOW_EUCALYPTUS_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_RAINBOW_EUCALYPTUS_LOG.getRegistryName()),
                BYGItemList.STRIPPED_SKYRIS_LOG = new BlockItem(BYGBlockList.STRIPPED_SKYRIS_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_SKYRIS_LOG.getRegistryName()),
                BYGItemList.STRIPPED_WILLOW_LOG = new BlockItem(BYGBlockList.STRIPPED_WILLOW_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_WILLOW_LOG.getRegistryName()),
                BYGItemList.STRIPPED_REDWOOD_LOG = new BlockItem(BYGBlockList.STRIPPED_REDWOOD_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_REDWOOD_LOG.getRegistryName()),
                BYGItemList.STRIPPED_WITCH_HAZEL_LOG = new BlockItem(BYGBlockList.STRIPPED_WITCH_HAZEL_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_WITCH_HAZEL_LOG.getRegistryName()),
                BYGItemList.STRIPPED_ZELKOVA_LOG = new BlockItem(BYGBlockList.STRIPPED_ZELKOVA_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.STRIPPED_ZELKOVA_LOG.getRegistryName()),

                //LeaveItems
                BYGItemList.ASPEN_LEAVES = new BlockItem(BYGBlockList.ASPEN_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ASPEN_LEAVES.getRegistryName()),
                BYGItemList.BAOBAB_LEAVES = new BlockItem(BYGBlockList.BAOBAB_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BAOBAB_LEAVES.getRegistryName()),
                BYGItemList.BLOOMING_WITCH_HAZEL_LEAVES = new BlockItem(BYGBlockList.BLOOMING_WITCH_HAZEL_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLOOMING_WITCH_HAZEL_LEAVES.getRegistryName()),
                BYGItemList.BLUE_ENCHANTED_LEAVES = new BlockItem(BYGBlockList.BLUE_ENCHANTED_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_ENCHANTED_LEAVES.getRegistryName()),
                BYGItemList.BLUE_SPRUCE_LEAVES = new BlockItem(BYGBlockList.BLUE_SPRUCE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_SPRUCE_LEAVES.getRegistryName()),
                BYGItemList.BROWN_BIRCH_LEAVES = new BlockItem(BYGBlockList.BROWN_BIRCH_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BROWN_BIRCH_LEAVES.getRegistryName()),
                BYGItemList.BROWN_OAK_LEAVES = new BlockItem(BYGBlockList.BROWN_OAK_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BROWN_OAK_LEAVES.getRegistryName()),
                BYGItemList.CIKA_LEAVES = new BlockItem(BYGBlockList.CIKA_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CIKA_LEAVES.getRegistryName()),
                BYGItemList.CYPRESS_LEAVES = new BlockItem(BYGBlockList.CYPRESS_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYPRESS_LEAVES.getRegistryName()),
                BYGItemList.EBONY_LEAVES = new BlockItem(BYGBlockList.EBONY_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.EBONY_LEAVES.getRegistryName()),
                BYGItemList.FIR_LEAVES = new BlockItem(BYGBlockList.FIR_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIR_LEAVES.getRegistryName()),
                BYGItemList.FLOWERING_ORCHARD_LEAVES = new BlockItem(BYGBlockList.FLOWERING_ORCHARD_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FLOWERING_ORCHARD_LEAVES.getRegistryName()),
                BYGItemList.FLOWERING_PALO_VERDE_LEAVES = new BlockItem(BYGBlockList.FLOWERING_PALO_VERDE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FLOWERING_PALO_VERDE_LEAVES.getRegistryName()),
                BYGItemList.GREEN_ENCHANTED_LEAVES = new BlockItem(BYGBlockList.GREEN_ENCHANTED_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_ENCHANTED_LEAVES.getRegistryName()),
                BYGItemList.HOLLY_BERRY_LEAVES = new BlockItem(BYGBlockList.HOLLY_BERRY_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_BERRY_LEAVES.getRegistryName()),
                BYGItemList.HOLLY_LEAVES = new BlockItem(BYGBlockList.HOLLY_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_LEAVES.getRegistryName()),
                BYGItemList.JACARANDA_LEAVES = new BlockItem(BYGBlockList.JACARANDA_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JACARANDA_LEAVES.getRegistryName()),
                BYGItemList.MAHOGANY_LEAVES = new BlockItem(BYGBlockList.MAHOGANY_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAHOGANY_LEAVES.getRegistryName()),
                BYGItemList.MANGROVE_LEAVES = new BlockItem(BYGBlockList.MANGROVE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MANGROVE_LEAVES.getRegistryName()),
                BYGItemList.ORANGE_BIRCH_LEAVES = new BlockItem(BYGBlockList.ORANGE_BIRCH_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORANGE_BIRCH_LEAVES.getRegistryName()),
                BYGItemList.ORANGE_OAK_LEAVES = new BlockItem(BYGBlockList.ORANGE_OAK_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORANGE_OAK_LEAVES.getRegistryName()),
                BYGItemList.ORANGE_SPRUCE_LEAVES = new BlockItem(BYGBlockList.ORANGE_SPRUCE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORANGE_SPRUCE_LEAVES.getRegistryName()),
                BYGItemList.ORCHARD_LEAVES = new BlockItem(BYGBlockList.ORCHARD_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORCHARD_LEAVES.getRegistryName()),
                BYGItemList.PALO_VERDE_LEAVES = new BlockItem(BYGBlockList.PALO_VERDE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PALO_VERDE_LEAVES.getRegistryName()),
                BYGItemList.PINE_lEAVES = new BlockItem(BYGBlockList.PINE_lEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINE_lEAVES.getRegistryName()),
                BYGItemList.PINK_CHERRY_LEAVES = new BlockItem(BYGBlockList.PINK_CHERRY_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINK_CHERRY_LEAVES.getRegistryName()),
                BYGItemList.RAINBOW_EUCALYPTUS_LEAVES = new BlockItem(BYGBlockList.RAINBOW_EUCALYPTUS_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RAINBOW_EUCALYPTUS_LEAVES.getRegistryName()),
                BYGItemList.RED_BIRCH_LEAVES = new BlockItem(BYGBlockList.RED_BIRCH_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_BIRCH_LEAVES.getRegistryName()),
                BYGItemList.RED_MAPLE_LEAVES = new BlockItem(BYGBlockList.RED_MAPLE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_MAPLE_LEAVES.getRegistryName()),
                BYGItemList.RED_OAK_LEAVES = new BlockItem(BYGBlockList.RED_OAK_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_OAK_LEAVES.getRegistryName()),
                BYGItemList.RED_SPRUCE_LEAVES = new BlockItem(BYGBlockList.RED_SPRUCE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_SPRUCE_LEAVES.getRegistryName()),
                BYGItemList.REDWOOD_LEAVES = new BlockItem(BYGBlockList.REDWOOD_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REDWOOD_LEAVES.getRegistryName()),
                BYGItemList.RIPE_ORCHARD_LEAVES = new BlockItem(BYGBlockList.RIPE_ORCHARD_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RIPE_ORCHARD_LEAVES.getRegistryName()),
                BYGItemList.SILVER_MAPLE_LEAVES = new BlockItem(BYGBlockList.SILVER_MAPLE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SILVER_MAPLE_LEAVES.getRegistryName()),
                BYGItemList.SKYRIS_LEAVES_GREEN_APPLE = new BlockItem(BYGBlockList.SKYRIS_LEAVES_GREEN_APPLE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_LEAVES_GREEN_APPLE.getRegistryName()),
                BYGItemList.SKYRIS_LEAVES = new BlockItem(BYGBlockList.SKYRIS_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_LEAVES.getRegistryName()),
                BYGItemList.WHITE_CHERRY_LEAVES = new BlockItem(BYGBlockList.WHITE_CHERRY_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WHITE_CHERRY_LEAVES.getRegistryName()),
                BYGItemList.WILLOW_LEAVES = new BlockItem(BYGBlockList.WILLOW_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WILLOW_LEAVES.getRegistryName()),
                BYGItemList.WITCH_HAZEL_LEAVES = new BlockItem(BYGBlockList.WITCH_HAZEL_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WITCH_HAZEL_LEAVES.getRegistryName()),
                BYGItemList.YELLOW_BIRCH_LEAVES = new BlockItem(BYGBlockList.YELLOW_BIRCH_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.YELLOW_BIRCH_LEAVES.getRegistryName()),
                BYGItemList.YELLOW_SPRUCE_LEAVES = new BlockItem(BYGBlockList.YELLOW_SPRUCE_LEAVES, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.YELLOW_SPRUCE_LEAVES.getRegistryName()),

                //LogItems
                BYGItemList.ASPEN_LOG = new BlockItem(BYGBlockList.ASPEN_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ASPEN_LOG.getRegistryName()),
                BYGItemList.BAOBAB_LOG = new BlockItem(BYGBlockList.BAOBAB_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BAOBAB_LOG.getRegistryName()),
                BYGItemList.BLUE_ENCHANTED_LOG = new BlockItem(BYGBlockList.BLUE_ENCHANTED_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_ENCHANTED_LOG.getRegistryName()),
                BYGItemList.CHERRY_LOG = new BlockItem(BYGBlockList.CHERRY_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CHERRY_LOG.getRegistryName()),
                BYGItemList.CIKA_LOG = new BlockItem(BYGBlockList.CIKA_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CIKA_LOG.getRegistryName()),
                BYGItemList.CYPRESS_LOG = new BlockItem(BYGBlockList.CYPRESS_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYPRESS_LOG.getRegistryName()),
                BYGItemList.EBONY_LOG = new BlockItem(BYGBlockList.EBONY_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.EBONY_LOG.getRegistryName()),
                BYGItemList.FIR_LOG = new BlockItem(BYGBlockList.FIR_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIR_LOG.getRegistryName()),
                BYGItemList.GREEN_ENCHANTED_LOG = new BlockItem(BYGBlockList.GREEN_ENCHANTED_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_ENCHANTED_LOG.getRegistryName()),
                BYGItemList.HOLLY_LOG = new BlockItem(BYGBlockList.HOLLY_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.HOLLY_LOG.getRegistryName()),
                BYGItemList.JACARANDA_LOG = new BlockItem(BYGBlockList.JACARANDA_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JACARANDA_LOG.getRegistryName()),
                BYGItemList.MAHOGANY_LOG = new BlockItem(BYGBlockList.MAHOGANY_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAHOGANY_LOG.getRegistryName()),
                BYGItemList.MANGROVE_LOG = new BlockItem(BYGBlockList.MANGROVE_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MANGROVE_LOG.getRegistryName()),
                BYGItemList.MAPLE_LOG = new BlockItem(BYGBlockList.MAPLE_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAPLE_LOG.getRegistryName()),
                BYGItemList.PALO_VERDE_LOG = new BlockItem(BYGBlockList.PALO_VERDE_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PALO_VERDE_LOG.getRegistryName()),
                BYGItemList.PINE_LOG = new BlockItem(BYGBlockList.PINE_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINE_LOG.getRegistryName()),
                BYGItemList.RAINBOW_EUCALYPTUS_LOG = new BlockItem(BYGBlockList.RAINBOW_EUCALYPTUS_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RAINBOW_EUCALYPTUS_LOG.getRegistryName()),
                BYGItemList.REDWOOD_LOG = new BlockItem(BYGBlockList.REDWOOD_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.REDWOOD_LOG.getRegistryName()),
                BYGItemList.SKYRIS_LOG = new BlockItem(BYGBlockList.SKYRIS_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SKYRIS_LOG.getRegistryName()),
                BYGItemList.WILLOW_LOG = new BlockItem(BYGBlockList.WILLOW_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WILLOW_LOG.getRegistryName()),
                BYGItemList.WITCH_HAZEL_LOG = new BlockItem(BYGBlockList.WITCH_HAZEL_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WITCH_HAZEL_LOG.getRegistryName()),
                BYGItemList.ZELKOVA_LOG = new BlockItem(BYGBlockList.ZELKOVA_LOG, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ZELKOVA_LOG.getRegistryName()),

                //FlowerItems
                BYGItemList.ALLIUM_FLOWER_BUSH = new BlockItem(BYGBlockList.ALLIUM_FLOWER_BUSH, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ALLIUM_FLOWER_BUSH.getRegistryName()),
                BYGItemList.ALPINE_BELLFLOWER = new BlockItem(BYGBlockList.ALPINE_BELLFLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ALPINE_BELLFLOWER.getRegistryName()),
                BYGItemList.PINK_ALLIUM_FLOWER_BUSH = new BlockItem(BYGBlockList.PINK_ALLIUM_FLOWER_BUSH, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINK_ALLIUM_FLOWER_BUSH.getRegistryName()),
                BYGItemList.ANGELICA = new BlockItem(BYGBlockList.ANGELICA, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ANGELICA.getRegistryName()),
                BYGItemList.AZALEA = new BlockItem(BYGBlockList.AZALEA, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.AZALEA.getRegistryName()),
                BYGItemList.BEGONIA = new BlockItem(BYGBlockList.BEGONIA, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BEGONIA.getRegistryName()),
                BYGItemList.BISTORT = new BlockItem(BYGBlockList.BISTORT, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BISTORT.getRegistryName()),
                BYGItemList.BLACK_ROSE = new BlockItem(BYGBlockList.BLACK_ROSE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLACK_ROSE.getRegistryName()),
                BYGItemList.BLUE_SAGE = new BlockItem(BYGBlockList.BLUE_SAGE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.BLUE_SAGE.getRegistryName()),
                BYGItemList.CALIFORNIA_POPPY = new BlockItem(BYGBlockList.CALIFORNIA_POPPY, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CALIFORNIA_POPPY.getRegistryName()),
                BYGItemList.CROCUS = new BlockItem(BYGBlockList.CROCUS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CROCUS.getRegistryName()),
                BYGItemList.CYAN_ROSE = new BlockItem(BYGBlockList.CYAN_ROSE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYAN_ROSE.getRegistryName()),
                BYGItemList.CYAN_TULIP = new BlockItem(BYGBlockList.CYAN_TULIP, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYAN_TULIP.getRegistryName()),
                BYGItemList.DAFFODIL = new BlockItem(BYGBlockList.DAFFODIL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.DAFFODIL.getRegistryName()),
                BYGItemList.DELPHINIUM = new BlockItem(BYGBlockList.DELPHINIUM, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.DELPHINIUM.getRegistryName()),
                BYGItemList.FAIRY_SLIPPER = new BlockItem(BYGBlockList.FAIRY_SLIPPER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FAIRY_SLIPPER.getRegistryName()),
                BYGItemList.FIRECRACKER_FLOWER_BUSH = new BlockItem(BYGBlockList.FIRECRACKER_FLOWER_BUSH, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FIRECRACKER_FLOWER_BUSH.getRegistryName()),
                BYGItemList.FOXGLOVE = new BlockItem(BYGBlockList.FOXGLOVE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.FOXGLOVE.getRegistryName()),
                BYGItemList.GOLDEN_SPINED_CACTUS = new BlockItem(BYGBlockList.GOLDEN_SPINED_CACTUS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GOLDEN_SPINED_CACTUS.getRegistryName()),
                BYGItemList.GREEN_TULIP = new BlockItem(BYGBlockList.GREEN_TULIP, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GREEN_TULIP.getRegistryName()),
                BYGItemList.GUZMANIA = new BlockItem(BYGBlockList.GUZMANIA, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.GUZMANIA.getRegistryName()),
                BYGItemList.INCAN_LILY = new BlockItem(BYGBlockList.INCAN_LILY, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.INCAN_LILY.getRegistryName()),
                BYGItemList.IRIS = new BlockItem(BYGBlockList.IRIS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.IRIS.getRegistryName()),
                BYGItemList.JAPANESE_ORCHID = new BlockItem(BYGBlockList.JAPANESE_ORCHID, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.JAPANESE_ORCHID.getRegistryName()),
                BYGItemList.KOVAN_FLOWER = new BlockItem(BYGBlockList.KOVAN_FLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.KOVAN_FLOWER.getRegistryName()),
                BYGItemList.LAZARUS_BELLFLOWER = new BlockItem(BYGBlockList.LAZARUS_BELLFLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.LAZARUS_BELLFLOWER.getRegistryName()),
                BYGItemList.LOLIPOP_FLOWER = new BlockItem(BYGBlockList.LOLIPOP_FLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.LOLIPOP_FLOWER.getRegistryName()),
                BYGItemList.MAGENTA_TULIP = new BlockItem(BYGBlockList.MAGENTA_TULIP, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAGENTA_TULIP.getRegistryName()),
                BYGItemList.ORANGE_DAISY = new BlockItem(BYGBlockList.ORANGE_DAISY, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORANGE_DAISY.getRegistryName()),
                BYGItemList.ORSIRIA_ROSE = new BlockItem(BYGBlockList.ORSIRIA_ROSE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORSIRIA_ROSE.getRegistryName()),
                BYGItemList.PEACH_LEATHER_FLOWER = new BlockItem(BYGBlockList.PEACH_LEATHER_FLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PEACH_LEATHER_FLOWER.getRegistryName()),
                BYGItemList.PINK_ALLIUM = new BlockItem(BYGBlockList.PINK_ALLIUM, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINK_ALLIUM.getRegistryName()),
                BYGItemList.PINK_ANEMONE = new BlockItem(BYGBlockList.PINK_ANEMONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINK_ANEMONE.getRegistryName()),
                BYGItemList.PINK_DAFFODIL = new BlockItem(BYGBlockList.PINK_DAFFODIL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINK_DAFFODIL.getRegistryName()),
                BYGItemList.PINK_ORCHID = new BlockItem(BYGBlockList.PINK_ORCHID, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PINK_ORCHID.getRegistryName()),
                BYGItemList.PRAIRIE_GRASS = new BlockItem(BYGBlockList.PRAIRIE_GRASS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PRAIRIE_GRASS.getRegistryName()),
                BYGItemList.PROTEA_FLOWER = new BlockItem(BYGBlockList.PROTEA_FLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PROTEA_FLOWER.getRegistryName()),
                BYGItemList.PURPLE_ORCHID = new BlockItem(BYGBlockList.PURPLE_ORCHID, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PURPLE_ORCHID.getRegistryName()),
                BYGItemList.PURPLE_SAGE = new BlockItem(BYGBlockList.PURPLE_SAGE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PURPLE_SAGE.getRegistryName()),
                BYGItemList.PURPLE_TULIP = new BlockItem(BYGBlockList.PURPLE_TULIP, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PURPLE_TULIP.getRegistryName()),
                BYGItemList.RED_CORNFLOWER = new BlockItem(BYGBlockList.RED_CORNFLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_CORNFLOWER.getRegistryName()),
                BYGItemList.RED_ORCHID = new BlockItem(BYGBlockList.RED_ORCHID, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RED_ORCHID.getRegistryName()),
                BYGItemList.RICHEA = new BlockItem(BYGBlockList.RICHEA, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.RICHEA.getRegistryName()),
                BYGItemList.ROSE = new BlockItem(BYGBlockList.ROSE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ROSE.getRegistryName()),
                BYGItemList.SILVER_VASE_FLOWER = new BlockItem(BYGBlockList.SILVER_VASE_FLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SILVER_VASE_FLOWER.getRegistryName()),
                BYGItemList.SNOWDROPS = new BlockItem(BYGBlockList.SNOWDROPS, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.SNOWDROPS.getRegistryName()),
                BYGItemList.TORCH_GINGER = new BlockItem(BYGBlockList.TORCH_GINGER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.TORCH_GINGER.getRegistryName()),
                BYGItemList.VIOLET_LEATHER_FLOWER = new BlockItem(BYGBlockList.VIOLET_LEATHER_FLOWER, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.VIOLET_LEATHER_FLOWER.getRegistryName()),
                BYGItemList.WHITE_ANEMONE = new BlockItem(BYGBlockList.WHITE_ANEMONE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WHITE_ANEMONE.getRegistryName()),
                BYGItemList.WHITE_SAGE = new BlockItem(BYGBlockList.WHITE_SAGE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WHITE_SAGE.getRegistryName()),
                BYGItemList.WINTER_CYCLAMEN = new BlockItem(BYGBlockList.WINTER_CYCLAMEN, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WINTER_CYCLAMEN.getRegistryName()),
                BYGItemList.WINTER_ROSE = new BlockItem(BYGBlockList.WINTER_ROSE, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WINTER_ROSE.getRegistryName()),
                BYGItemList.WINTER_SCILLA = new BlockItem(BYGBlockList.WINTER_SCILLA, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.WINTER_SCILLA.getRegistryName()),
                BYGItemList.YELLOW_DAFFODIL = new BlockItem(BYGBlockList.YELLOW_DAFFODIL, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.YELLOW_DAFFODIL.getRegistryName()),
                BYGItemList.YELLOW_TULIP = new BlockItem(BYGBlockList.YELLOW_TULIP, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.YELLOW_TULIP.getRegistryName()),
                BYGItemList.AMARANTH = new BlockItem(BYGBlockList.AMARANTH, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.AMARANTH.getRegistryName()),
                BYGItemList.CYAN_AMARANTH = new BlockItem(BYGBlockList.CYAN_AMARANTH, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.CYAN_AMARANTH.getRegistryName()),
                BYGItemList.ORANGE_AMARANTH = new BlockItem(BYGBlockList.ORANGE_AMARANTH, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.ORANGE_AMARANTH.getRegistryName()),
                BYGItemList.MAGENTA_AMARANTH = new BlockItem(BYGBlockList.MAGENTA_AMARANTH, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.MAGENTA_AMARANTH.getRegistryName()),
                BYGItemList.PURPLE_AMARANTH = new BlockItem(BYGBlockList.PURPLE_AMARANTH, new Item.Properties().group(BYG.Init.creativeTab)).setRegistryName(BYGBlockList.PURPLE_AMARANTH.getRegistryName())
        );
        BYG.LOGGER.info("All BYG items registered!");
    }
}
