package sporeaoc.byg;

import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;
import net.minecraft.potion.Effects;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import sporeaoc.byg.block.*;
import sporeaoc.byg.items.*;


public class BlockItemRegistry {
    @Mod.EventBusSubscriber(bus=Mod.EventBusSubscriber.Bus.MOD)
    public static class RegistryEvents {

    @SubscribeEvent
    public static void bygRegisterBlocks(final RegistryEvent.Register<Block> event) {


        event.getRegistry().registerAll
                (
                PlankBlocks.ASPEN_PLANKS = new Block(Block.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("aspen_planks"),
                PlankBlocks.BAOBAB_PLANKS = new Block(Block.Properties.create(Material.WOOD, MaterialColor.BROWN).hardnessAndResistance(2.0F, 3.0F).sound(SoundType.WOOD)).setRegistryName("baobab_planks"),
                PlankBlocks.BLUE_ENCHANTED_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("blue_enchanted_planks"),
                PlankBlocks.CHERRY_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("cherry_planks"),
                PlankBlocks.CIKA_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("cika_planks"),
                PlankBlocks.CYPRESS_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("cypress_planks"),
                PlankBlocks.EBONY_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("ebony_planks"),
                PlankBlocks.FIR_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("fir_planks"),
                PlankBlocks.GREEN_ENCHANTED_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("green_enchanted_planks"),
                PlankBlocks.HOLLY_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("holly_planks"),
                PlankBlocks.JACARANDA_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("jacaranda_planks"),
                PlankBlocks.MAHOGONY_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("mahogany_planks"),
                PlankBlocks.MANGROVE_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("mangrove_planks"),
                PlankBlocks.MAPLE_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("maple_planks"),
                PlankBlocks.PINE_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("pine_planks"),
                PlankBlocks.RAINBOW_EUCALYPTUS_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("rainbow_eucalyptus_planks"),
                PlankBlocks.REDWOOD_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("redwood_planks"),
                PlankBlocks.SKYRIS_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("skyris_planks"),
                PlankBlocks.WILLOW_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("willow_planks"),
                PlankBlocks.WITCH_HAZEL_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("witch_hazel_planks"),
                PlankBlocks.ZELKOVA_PLANKS = new Block(Block.Properties.create(Material.WOOD,MaterialColor.BROWN).hardnessAndResistance(2.0F,3.0F).sound(SoundType.WOOD)).setRegistryName("zelkova_planks"),

                //FenceBlocks
                //FenceBlocks.ASPEN_FENCE = new FenceBlock(Block.Properties.create(Material.WOOD, OAK))
                //LeaveBlocks
                LeaveBlocks.APPLE_SKYRIS_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("apple_skyris_leaves")),
                LeaveBlocks.BAOBAB_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("baobab_leaves")),
                LeaveBlocks.BLOOMING_WITCH_HAZEL_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("blooming_witch_hazel_leaves")),
                LeaveBlocks.BLUE_ENCHANTED_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("blue_enchanted_leaves")),
                LeaveBlocks.BLUE_SPRUCE_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("blue_spruce_leaves")),
                LeaveBlocks.BROWN_BIRCH_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("brown_birch_leaves")),
                LeaveBlocks.BROWN_OAK_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("brown_oak_leaves")),
                LeaveBlocks.CIKA_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("cika_leaves")),
                LeaveBlocks.CYPRESS_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("cypress_leaves")),
                LeaveBlocks.EBONY_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("ebony_leaves")),
                LeaveBlocks.FIR_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("fir_leaves")),
                LeaveBlocks.FLOWERING_ORCHARD_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("flowering_orchard_leaves")),
                LeaveBlocks.FLOWERING_PALO_VERDE_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("flowering_palo_verde_leaves")),
                LeaveBlocks.GREEN_ENCHANTED_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("green_enchanted_leaves")),
                LeaveBlocks.HOLLY_BETTER_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("holly_berry_leaves")),
                LeaveBlocks.HOLLY_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("holly_leaves")),
                LeaveBlocks.JACARANDA_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("jacaranda_leaves")),
                LeaveBlocks.MAHOGANY_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("mahogany_leaves")),
                LeaveBlocks.MANGROVE_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("mangrove_leaves")),
                LeaveBlocks.ORANGE_BIRCH_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("orange_birch_leaves")),
                LeaveBlocks.ORANGE_OAK_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("orange_oak_leaves")),
                LeaveBlocks.ORANGE_SPRUCE_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("orange_spruce_leaves")),
                LeaveBlocks.ORCHARD_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("orchard_leaves")),
                LeaveBlocks.PALO_VERDE_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("palo_verde_leaves")),
                LeaveBlocks.PINE_lEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("pine_leaves")),
                LeaveBlocks.PINK_CHERRY_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("pink_cherry_leaves")),
                LeaveBlocks.RAINBOW_EUCALYPTUS_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("rainbow_eucalyptus_leaves")),
                LeaveBlocks.RED_BIRCH_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("red_birch_leaves")),
                LeaveBlocks.RED_MAPLE_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("red_maple_leaves")),
                LeaveBlocks.RED_OAK_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("red_oak_leaves")),
                LeaveBlocks.RED_SPRUCE_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("red_spruce_leaves")),
                LeaveBlocks.REDWOOD_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("redwood_leaves")),
                LeaveBlocks.RIPE_ORCHARD_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("ripe_orchard_leaves")),
                LeaveBlocks.SILVER_MAPLE_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("silver_maple_leaves")),
                LeaveBlocks.SKYRIS_LEAVES_GREEN_APPLE = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("green_apple_skyris_leaves")),
                LeaveBlocks.WHITE_CHERRY_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("white_cherry_leaves")),
                LeaveBlocks.WILLOW_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("willow_leaves")),
                LeaveBlocks.WITCH_HAZEL_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("witch_hazel_leaves")),
                LeaveBlocks.YELLOW_BIRCH_LEAVES = new LeavesBlock(Block.Properties.create(Material.LEAVES).hardnessAndResistance(0.2F).tickRandomly().sound(SoundType.PLANT)).setRegistryName(location("yellow_birch_leaves")),

                //LogBlocks
                LogBlocks.ASPEN_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("aspen_log")),
                LogBlocks.BAOBAB_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("baobab_log")),
                LogBlocks.BLUE_ENCHANTED_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("blue_enchanted_log")),
                LogBlocks.CHERRY_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("cherry_log")),
                LogBlocks.CIKA_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("cika_log")),
                LogBlocks.CYPRESS_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("cypress_log")),
                LogBlocks.EBONY_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("ebony_log")),
                LogBlocks.FIR_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("fir_log")),
                LogBlocks.GREEN_ENCHANTED_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("green_enchanted_log")),
                LogBlocks.HOLLY_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("holly_log")),
                LogBlocks.JACARANDA_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("jacaranda_log")),
                LogBlocks.MAHOGANY_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("mahogany_log")),
                LogBlocks.MANGROVE_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("mangrove_log")),
                LogBlocks.MAPLE_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("maple_log")),
                LogBlocks.PALO_VERDE_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("palo_verde_log")),
                LogBlocks.PINE_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("pine_log")),
                LogBlocks.RAINBOW_EUCALYPTUS_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("rainbow_eucalyptus_log")),
                LogBlocks.REDWOOD_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("redwood_log")),
                LogBlocks.SKYRIS_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("skyris_log")),
                LogBlocks.WILLOW_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("willow_log")),
                LogBlocks.WITCH_HAZEL_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("witch_hazel_log")),
                LogBlocks.ZELKOVA_LOG = new LogBlock(MaterialColor.WOOD, Block.Properties.create(Material.WOOD, MaterialColor.WOOD).hardnessAndResistance(2.0F).sound(SoundType.WOOD)).setRegistryName(location("zelkova_log")),

                //OreBlocks
                OreBlocks.LATHARIUM_ORE = new OreBlock(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F)).setRegistryName(location("latharium_ore")),
                OreBlocks.PENDORITE_ORE = new OreBlock(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F)).setRegistryName(location("pendorite_ore")),
                OreBlocks.TAMRELITE_ORE = new OreBlock(Block.Properties.create(Material.ROCK).hardnessAndResistance(3.0F, 3.0F)).setRegistryName(location("tamrelite_ore")),

                //StoneBlocks
                StoneBlocks.DACITE_STONE = new Block(Block.Properties.create(Material.ROCK, MaterialColor.STONE).hardnessAndResistance(1.5F, 6.0F)).setRegistryName(location("dacite_stone")),
                StoneBlocks.MOSSY_STONE = new Block(Block.Properties.create(Material.ROCK, MaterialColor.STONE).hardnessAndResistance(1.5F, 6.0F)).setRegistryName(location("mossy_stone")),
                StoneBlocks.OVERGROWN_STONE = new Block(Block.Properties.create(Material.ROCK, MaterialColor.STONE).hardnessAndResistance(1.5F, 6.0F)).setRegistryName(location("overgrown_stone")),
                StoneBlocks.SCORIA_STONE = new Block(Block.Properties.create(Material.ROCK, MaterialColor.STONE).hardnessAndResistance(1.5F, 6.0F)).setRegistryName(location("scoria_stone")),
                StoneBlocks.SOAPSTONE = new Block(Block.Properties.create(Material.ROCK, MaterialColor.STONE).hardnessAndResistance(1.5F, 6.0F)).setRegistryName(location("soapstone")),
                StoneBlocks.SODALITE = new Block(Block.Properties.create(Material.ROCK, MaterialColor.STONE).hardnessAndResistance(1.5F, 6.0F)).setRegistryName(location("sodalite")),


                //FlowerBlocks
                FlowerBlocks.ALLIUM_FLOWER_BUSH = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("allium_flower_bush")),
                FlowerBlocks.ALPINE_BELLFLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("alpine_bellflower")),
                FlowerBlocks.AMARANTH = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("amaranth")),
                FlowerBlocks.ANGELICA = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("angelica")),
                FlowerBlocks.AZALEA = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("azalea")),
                FlowerBlocks.BEGONIA = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("begonia")),
                FlowerBlocks.BISTORT = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("bistort")),
                FlowerBlocks.BLUE_SAGE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("blue_sage")),
                FlowerBlocks.CALIFORNIA_POPPY = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("california_poppy")),
                FlowerBlocks.CROCUS = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("crocus")),
                FlowerBlocks.BLACK_ROSE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("black_rose")),
                FlowerBlocks.CYAN_AMARANTH = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("cyan_amaranth")),
                FlowerBlocks.CYAN_ROSE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("cyan_rose")),
                FlowerBlocks.CYAN_TULIP = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("cyan_tulip")),
                FlowerBlocks.DAFFODIL = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("daffodil")),
                FlowerBlocks.DELPHINIUM = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("delphinium")),
                FlowerBlocks.FAIRY_SLIPPER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("fairy_slipper")),
                FlowerBlocks.FIRECRACKER_FLOWER_BUSH = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("firecracker_flower_bush")),
                FlowerBlocks.FOXGLOVE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("foxglove")),
                FlowerBlocks.GOLDEN_SPINED_CACTUS = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("golden_spined_cactus")),
                FlowerBlocks.GREEN_TULIP = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("green_tulip")),
                FlowerBlocks.GUZMANIA = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("guzmania")),
                FlowerBlocks.INCAN_LILY = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("incan_lily")),
                FlowerBlocks.IRIS = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("iris")),
                FlowerBlocks.JAPANESE_ORCHID = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("japanese_orchid")),
                FlowerBlocks.KOVAN_FLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("kovan_flower")),
                FlowerBlocks.LAZARUS_BELLFLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("lazarus_bellflower")),
                FlowerBlocks.LOLIPOP_FLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("lolipop_flower")),
                FlowerBlocks.MAGENTA_AMARANTH = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("magenta_amaranth")),
                FlowerBlocks.MAGENTA_TULIP = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("magenta_tulip")),
                FlowerBlocks.ORANGE_AMARANTH = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("orange_amaranth")),
                FlowerBlocks.ORANGE_DAISY = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("orange_daisy")),
                FlowerBlocks.ORSIRIA_ROSE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("osiria_rose")),
                FlowerBlocks.PEACH_LEATHER_FLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("peach_leather_flower")),
                FlowerBlocks.PINK_ALLIUM = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("pink_allium")),
                FlowerBlocks.PINK_ALLIUM_FLOWER_BUSH = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("pink_allium_flower_bush")),
                FlowerBlocks.PINK_ANEMONE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("pink_anemone")),
                FlowerBlocks.PINK_DAFFODIL = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("pink_daffodil")),
                FlowerBlocks.PINK_ORCHID = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("pink_orchid")),
                FlowerBlocks.PROTEA_FLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("protea_flower")),
                FlowerBlocks.PURPLE_AMARANTH = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("purple_amaranth")),
                FlowerBlocks.PURPLE_ORCHID = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("purple_orchid")),
                FlowerBlocks.PURPLE_SAGE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("purple_sage")),
                FlowerBlocks.PURPLE_TULIP = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("purple_tulip")),
                FlowerBlocks.RED_CORNFLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("red_cornflower")),
                FlowerBlocks.RED_ORCHID = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("red_orchid")),
                FlowerBlocks.RICHEA = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("richea")),
                FlowerBlocks.ROSE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("rose")),
                FlowerBlocks.SNOWDROPS = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("snowdrops")),
                FlowerBlocks.SILVER_VASE_FLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("silver_vase_flower")),
                FlowerBlocks.TORCH_GINGER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("torch_ginger")),
                FlowerBlocks.VIOLET_LEATHER_FLOWER = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("violet_leather_flower")),
                FlowerBlocks.WHITE_ANEMONE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("white_anemone")),
                FlowerBlocks.WHITE_SAGE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("white_sage")),
                FlowerBlocks.WINTER_CYCLAMEN = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("winter_cyclamen")),
                FlowerBlocks.WINTER_ROSE = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("winter_rose")),
                FlowerBlocks.WINTER_SCILLA = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("winter_scilla")),
                FlowerBlocks.YELLOW_DAFFODIL = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("yellow_daffodil")),
                FlowerBlocks.YELLOW_TULIP = new FlowerBlock(Effects.SATURATION, 7, Block.Properties.create(Material.PLANTS).doesNotBlockMovement().hardnessAndResistance(0.0f).sound(SoundType.PLANT)).setRegistryName(location("yellow_tulip"))
                );
        BYG.LOGGER.info("Load Blocks");
    }

    @SubscribeEvent
    public static void bygRegisterItems(final RegistryEvent.Register<Item> event) {
        event.getRegistry().registerAll
                (

                PlankItems.ASPEN_PLANKS = new BlockItem(PlankBlocks.ASPEN_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.ASPEN_PLANKS.getRegistryName()),
                PlankItems.BAOBAB_PLANKS = new BlockItem(PlankBlocks.BAOBAB_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.BAOBAB_PLANKS.getRegistryName()),
                PlankItems.BLUE_ENCHANTED_PLANKS = new BlockItem(PlankBlocks.BLUE_ENCHANTED_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.BLUE_ENCHANTED_PLANKS.getRegistryName()),
                PlankItems.CHERRY_PLANKS = new BlockItem(PlankBlocks.CHERRY_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.CHERRY_PLANKS.getRegistryName()),
                PlankItems.CIKA_PLANKS = new BlockItem(PlankBlocks.CIKA_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.CIKA_PLANKS.getRegistryName()),
                PlankItems.CYPRESS_PLANKS = new BlockItem(PlankBlocks.CYPRESS_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.CYPRESS_PLANKS.getRegistryName()),
                PlankItems.EBONY_PLANKS = new BlockItem(PlankBlocks.EBONY_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.EBONY_PLANKS.getRegistryName()),
                PlankItems.FIR_PLANKS = new BlockItem(PlankBlocks.FIR_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.FIR_PLANKS.getRegistryName()),
                PlankItems.GREEN_ENCHANTED_PLANKS = new BlockItem(PlankBlocks.GREEN_ENCHANTED_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.GREEN_ENCHANTED_PLANKS.getRegistryName()),
                PlankItems.HOLLY_PLANKS = new BlockItem(PlankBlocks.HOLLY_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.HOLLY_PLANKS.getRegistryName()),
                PlankItems.JACARANDA_PLANKS = new BlockItem(PlankBlocks.JACARANDA_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.JACARANDA_PLANKS.getRegistryName()),
                PlankItems.MAHOGONY_PLANKS = new BlockItem(PlankBlocks.MAHOGONY_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.MAHOGONY_PLANKS.getRegistryName()),
                PlankItems.MANGROVE_PLANKS = new BlockItem(PlankBlocks.MANGROVE_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.MANGROVE_PLANKS.getRegistryName()),
                PlankItems.MAPLE_PLANKS = new BlockItem(PlankBlocks.MAPLE_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.MAPLE_PLANKS.getRegistryName()),
                PlankItems.PINE_PLANKS = new BlockItem(PlankBlocks.PINE_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.PINE_PLANKS.getRegistryName()),
                PlankItems.RAINBOW_EUCALYPTUS_PLANKS = new BlockItem(PlankBlocks.RAINBOW_EUCALYPTUS_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.RAINBOW_EUCALYPTUS_PLANKS.getRegistryName()),
                PlankItems.REDWOOD_PLANKS = new BlockItem(PlankBlocks.REDWOOD_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.REDWOOD_PLANKS.getRegistryName()),
                PlankItems.SKYRIS_PLANKS = new BlockItem(PlankBlocks.SKYRIS_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.SKYRIS_PLANKS.getRegistryName()),
                PlankItems.WILLOW_PLANKS = new BlockItem(PlankBlocks.WILLOW_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.WILLOW_PLANKS.getRegistryName()),
                PlankItems.WITCH_HAZEL_PLANKS = new BlockItem(PlankBlocks.WITCH_HAZEL_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.WITCH_HAZEL_PLANKS.getRegistryName()),
                PlankItems.ZELKOVA_PLANKS = new BlockItem(PlankBlocks.ZELKOVA_PLANKS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(PlankBlocks.ZELKOVA_PLANKS.getRegistryName()),

                //OreItems
                        OreItems.LATHARIUM_ORE = new BlockItem(OreBlocks.LATHARIUM_ORE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(OreBlocks.LATHARIUM_ORE.getRegistryName()),
                        OreItems.PENDORITE_ORE = new BlockItem(OreBlocks.PENDORITE_ORE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(OreBlocks.PENDORITE_ORE.getRegistryName()),
                        OreItems.TAMRELITE_ORE = new BlockItem(OreBlocks.TAMRELITE_ORE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(OreBlocks.TAMRELITE_ORE.getRegistryName()),


                LeaveItems.APPLE_SKYRIS_LEAVES = new BlockItem(LeaveBlocks.APPLE_SKYRIS_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.APPLE_SKYRIS_LEAVES.getRegistryName()),
                LeaveItems.BAOBAB_LEAVES = new BlockItem(LeaveBlocks.BAOBAB_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.BAOBAB_LEAVES.getRegistryName()),
                LeaveItems.BLOOMING_WITCH_HAZEL_LEAVES = new BlockItem(LeaveBlocks.BLOOMING_WITCH_HAZEL_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.BLOOMING_WITCH_HAZEL_LEAVES.getRegistryName()),
                LeaveItems.BLUE_ENCHANTED_LEAVES = new BlockItem(LeaveBlocks.BLUE_ENCHANTED_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.BLUE_ENCHANTED_LEAVES.getRegistryName()),
                LeaveItems.BLUE_SPRUCE_LEAVES = new BlockItem(LeaveBlocks.BLUE_SPRUCE_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.BLUE_SPRUCE_LEAVES.getRegistryName()),
                LeaveItems.BROWN_BIRCH_LEAVES = new BlockItem(LeaveBlocks.BROWN_BIRCH_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.BROWN_BIRCH_LEAVES.getRegistryName()),
                LeaveItems.BROWN_OAK_LEAVES = new BlockItem(LeaveBlocks.BROWN_OAK_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.BROWN_OAK_LEAVES.getRegistryName()),
                LeaveItems.CIKA_LEAVES = new BlockItem(LeaveBlocks.CIKA_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.CIKA_LEAVES.getRegistryName()),
                LeaveItems.CYPRESS_LEAVES = new BlockItem(LeaveBlocks.CYPRESS_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.CYPRESS_LEAVES.getRegistryName()),
                LeaveItems.EBONY_LEAVES = new BlockItem(LeaveBlocks.EBONY_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.EBONY_LEAVES.getRegistryName()),
                LeaveItems.FIR_LEAVES = new BlockItem(LeaveBlocks.FIR_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.FIR_LEAVES.getRegistryName()),
                LeaveItems.FLOWERING_ORCHARD_LEAVES = new BlockItem(LeaveBlocks.FLOWERING_ORCHARD_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.FLOWERING_ORCHARD_LEAVES.getRegistryName()),
                LeaveItems.FLOWERING_PALO_VERDE_LEAVES = new BlockItem(LeaveBlocks.FLOWERING_PALO_VERDE_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.FLOWERING_PALO_VERDE_LEAVES.getRegistryName()),
                LeaveItems.GREEN_ENCHANTED_LEAVES = new BlockItem(LeaveBlocks.GREEN_ENCHANTED_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.GREEN_ENCHANTED_LEAVES.getRegistryName()),
                LeaveItems.HOLLY_BETTER_LEAVES = new BlockItem(LeaveBlocks.HOLLY_BETTER_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.HOLLY_BETTER_LEAVES.getRegistryName()),
                LeaveItems.HOLLY_LEAVES = new BlockItem(LeaveBlocks.HOLLY_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.HOLLY_LEAVES.getRegistryName()),
                LeaveItems.JACARANDA_LEAVES = new BlockItem(LeaveBlocks.JACARANDA_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.JACARANDA_LEAVES.getRegistryName()),
                LeaveItems.MAHOGANY_LEAVES = new BlockItem(LeaveBlocks.MAHOGANY_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.MAHOGANY_LEAVES.getRegistryName()),
                LeaveItems.MANGROVE_LEAVES = new BlockItem(LeaveBlocks.MANGROVE_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.MANGROVE_LEAVES.getRegistryName()),
                LeaveItems.ORANGE_BIRCH_LEAVES = new BlockItem(LeaveBlocks.ORANGE_BIRCH_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.ORANGE_BIRCH_LEAVES.getRegistryName()),
                LeaveItems.ORANGE_OAK_LEAVES = new BlockItem(LeaveBlocks.ORANGE_OAK_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.ORANGE_OAK_LEAVES.getRegistryName()),
                LeaveItems.ORANGE_SPRUCE_LEAVES = new BlockItem(LeaveBlocks.ORANGE_SPRUCE_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.ORANGE_SPRUCE_LEAVES.getRegistryName()),
                LeaveItems.ORCHARD_LEAVES = new BlockItem(LeaveBlocks.ORCHARD_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.ORCHARD_LEAVES.getRegistryName()),
                LeaveItems.PALO_VERDE_LEAVES = new BlockItem(LeaveBlocks.PALO_VERDE_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.PALO_VERDE_LEAVES.getRegistryName()),
                LeaveItems.PINE_lEAVES = new BlockItem(LeaveBlocks.PINE_lEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.PINE_lEAVES.getRegistryName()),
                LeaveItems.PINK_CHERRY_LEAVES = new BlockItem(LeaveBlocks.PINK_CHERRY_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.PINK_CHERRY_LEAVES.getRegistryName()),
                LeaveItems.RAINBOW_EUCALYPTUS_LEAVES = new BlockItem(LeaveBlocks.RAINBOW_EUCALYPTUS_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.RAINBOW_EUCALYPTUS_LEAVES.getRegistryName()),
                LeaveItems.RED_BIRCH_LEAVES = new BlockItem(LeaveBlocks.RED_BIRCH_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.RED_BIRCH_LEAVES.getRegistryName()),
                LeaveItems.RED_MAPLE_LEAVES = new BlockItem(LeaveBlocks.RED_MAPLE_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.RED_MAPLE_LEAVES.getRegistryName()),
                LeaveItems.RED_OAK_LEAVES = new BlockItem(LeaveBlocks.RED_OAK_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.RED_OAK_LEAVES.getRegistryName()),
                LeaveItems.RED_SPRUCE_LEAVES = new BlockItem(LeaveBlocks.RED_SPRUCE_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.RED_SPRUCE_LEAVES.getRegistryName()),
                LeaveItems.REDWOOD_LEAVES = new BlockItem(LeaveBlocks.REDWOOD_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.REDWOOD_LEAVES.getRegistryName()),
                LeaveItems.RIPE_ORCHARD_LEAVES = new BlockItem(LeaveBlocks.RIPE_ORCHARD_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.RIPE_ORCHARD_LEAVES.getRegistryName()),
                LeaveItems.SILVER_MAPLE_LEAVES = new BlockItem(LeaveBlocks.SILVER_MAPLE_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.SILVER_MAPLE_LEAVES.getRegistryName()),
                LeaveItems.SKYRIS_LEAVES_GREEN_APPLE = new BlockItem(LeaveBlocks.SKYRIS_LEAVES_GREEN_APPLE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.SKYRIS_LEAVES_GREEN_APPLE.getRegistryName()),
                LeaveItems.WHITE_CHERRY_LEAVES = new BlockItem(LeaveBlocks.WHITE_CHERRY_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.WHITE_CHERRY_LEAVES.getRegistryName()),
                LeaveItems.WILLOW_LEAVES = new BlockItem(LeaveBlocks.WILLOW_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.WILLOW_LEAVES.getRegistryName()),
                LeaveItems.WITCH_HAZEL_LEAVES = new BlockItem(LeaveBlocks.WITCH_HAZEL_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.WITCH_HAZEL_LEAVES.getRegistryName()),
                LeaveItems.YELLOW_BIRCH_LEAVES = new BlockItem(LeaveBlocks.YELLOW_BIRCH_LEAVES, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LeaveBlocks.YELLOW_BIRCH_LEAVES.getRegistryName()),

                //Logs
                LogItems.ASPEN_LOG = new BlockItem(LogBlocks.ASPEN_LOG, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.ASPEN_LOG.getRegistryName()),
                LogItems.BAOBAB_LOG = new BlockItem(LogBlocks.BAOBAB_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.BAOBAB_LOG.getRegistryName()),
                LogItems.BLUE_ENCHANTED_LOG = new BlockItem(LogBlocks.BLUE_ENCHANTED_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.BLUE_ENCHANTED_LOG.getRegistryName()),
                LogItems.CHERRY_LOG = new BlockItem(LogBlocks.CHERRY_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.CHERRY_LOG.getRegistryName()),
                LogItems.CIKA_LOG = new BlockItem(LogBlocks.CIKA_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.CIKA_LOG.getRegistryName()),
                LogItems.CYPRESS_LOG= new BlockItem(LogBlocks.CYPRESS_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.CYPRESS_LOG.getRegistryName()),
                LogItems.EBONY_LOG = new BlockItem(LogBlocks.EBONY_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.EBONY_LOG.getRegistryName()),
                LogItems.FIR_LOG = new BlockItem(LogBlocks.FIR_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.FIR_LOG.getRegistryName()),
                LogItems.GREEN_ENCHANTED_LOG = new BlockItem(LogBlocks.GREEN_ENCHANTED_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.GREEN_ENCHANTED_LOG.getRegistryName()),
                LogItems.HOLLY_LOG = new BlockItem(LogBlocks.HOLLY_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.HOLLY_LOG.getRegistryName()),
                LogItems.JACARANDA_LOG = new BlockItem(LogBlocks.JACARANDA_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.JACARANDA_LOG.getRegistryName()),
                LogItems.MAHOGANY_LOG = new BlockItem(LogBlocks.MAHOGANY_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.MAHOGANY_LOG.getRegistryName()),
                LogItems.MANGROVE_LOG = new BlockItem(LogBlocks.MANGROVE_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.MANGROVE_LOG.getRegistryName()),
                LogItems.MAPLE_LOG = new BlockItem(LogBlocks.MAPLE_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.MAPLE_LOG.getRegistryName()),
                LogItems.PALO_VERDE_LOG = new BlockItem(LogBlocks.PALO_VERDE_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.PALO_VERDE_LOG.getRegistryName()),
                LogItems.PINE_LOG = new BlockItem(LogBlocks.PINE_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.PINE_LOG.getRegistryName()),
                LogItems.RAINBOW_EUCALYPTUS_LOG = new BlockItem(LogBlocks.RAINBOW_EUCALYPTUS_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.RAINBOW_EUCALYPTUS_LOG.getRegistryName()),
                LogItems.REDWOOD_LOG = new BlockItem(LogBlocks.REDWOOD_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.REDWOOD_LOG.getRegistryName()),
                LogItems.SKYRIS_LOG = new BlockItem(LogBlocks.SKYRIS_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.SKYRIS_LOG.getRegistryName()),
                LogItems.WILLOW_LOG = new BlockItem(LogBlocks.WILLOW_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.WILLOW_LOG.getRegistryName()),
                LogItems.WITCH_HAZEL_LOG = new BlockItem(LogBlocks.WITCH_HAZEL_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.WITCH_HAZEL_LOG.getRegistryName()),
                LogItems.ZELKOVA_LOG = new BlockItem(LogBlocks.ZELKOVA_LOG , new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(LogBlocks.ZELKOVA_LOG.getRegistryName()),

                                // Capital Letters only for FLOWER_NAME  ////
                //Flower   FlowerItems.<FLOWER_NAME>= new BlockItem(FlowerBlocks.<FLOWER_NAME>, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(.setRegistryName(FlowerBlocks.<FLOWER_NAME>.getRegistryName()),
                FlowerItems.ALLIUM_FLOWER_BUSH = new BlockItem(FlowerBlocks.ALLIUM_FLOWER_BUSH, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.ALLIUM_FLOWER_BUSH.getRegistryName()),
                FlowerItems.ALPINE_BELLFLOWER = new BlockItem(FlowerBlocks.ALPINE_BELLFLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.ALPINE_BELLFLOWER.getRegistryName()),
                FlowerItems.PINK_ALLIUM_FLOWER_BUSH = new BlockItem(FlowerBlocks.PINK_ALLIUM_FLOWER_BUSH, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PINK_ALLIUM_FLOWER_BUSH.getRegistryName()),
                FlowerItems.ANGELICA = new BlockItem(FlowerBlocks.ANGELICA, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.ANGELICA.getRegistryName()),
                FlowerItems.AZALEA = new BlockItem(FlowerBlocks.AZALEA, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.AZALEA.getRegistryName()),
                FlowerItems.BEGONIA = new BlockItem(FlowerBlocks.BEGONIA, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.BEGONIA.getRegistryName()),
                FlowerItems.BISTORT = new BlockItem(FlowerBlocks.BISTORT, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.BISTORT.getRegistryName()),
                FlowerItems.BLACK_ROSE = new BlockItem(FlowerBlocks.BLACK_ROSE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.BLACK_ROSE.getRegistryName()),
                FlowerItems.BLUE_SAGE = new BlockItem(FlowerBlocks.BLUE_SAGE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.BLUE_SAGE.getRegistryName()),
                FlowerItems.CALIFORNIA_POPPY = new BlockItem(FlowerBlocks.CALIFORNIA_POPPY, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.CALIFORNIA_POPPY.getRegistryName()),
                FlowerItems.CROCUS = new BlockItem(FlowerBlocks.CROCUS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.CROCUS.getRegistryName()),
                FlowerItems.CYAN_ROSE = new BlockItem(FlowerBlocks.CYAN_ROSE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.CYAN_ROSE.getRegistryName()),
                FlowerItems.CYAN_TULIP = new BlockItem(FlowerBlocks.CYAN_TULIP, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.CYAN_TULIP.getRegistryName()),
                FlowerItems.DAFFODIL = new BlockItem(FlowerBlocks.DAFFODIL, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.DAFFODIL.getRegistryName()),
                FlowerItems.DELPHINIUM = new BlockItem(FlowerBlocks.DELPHINIUM, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.DELPHINIUM.getRegistryName()),
                FlowerItems.FAIRY_SLIPPER = new BlockItem(FlowerBlocks.FAIRY_SLIPPER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.FAIRY_SLIPPER.getRegistryName()),
                FlowerItems.FIRECRACKER_FLOWER_BUSH = new BlockItem(FlowerBlocks.FIRECRACKER_FLOWER_BUSH, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.FIRECRACKER_FLOWER_BUSH.getRegistryName()),
                FlowerItems.FOXGLOVE = new BlockItem(FlowerBlocks.FOXGLOVE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.FOXGLOVE.getRegistryName()),
                FlowerItems.GOLDEN_SPINED_CACTUS = new BlockItem(FlowerBlocks.GOLDEN_SPINED_CACTUS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.GOLDEN_SPINED_CACTUS.getRegistryName()),
                FlowerItems.GREEN_TULIP = new BlockItem(FlowerBlocks.GREEN_TULIP, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.GREEN_TULIP.getRegistryName()),
                FlowerItems.GUZMANIA = new BlockItem(FlowerBlocks.GUZMANIA, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.GUZMANIA.getRegistryName()),
                FlowerItems.INCAN_LILY = new BlockItem(FlowerBlocks.INCAN_LILY, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.INCAN_LILY.getRegistryName()),
                FlowerItems.IRIS = new BlockItem(FlowerBlocks.IRIS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.IRIS.getRegistryName()),
                FlowerItems.JAPANESE_ORCHID = new BlockItem(FlowerBlocks.JAPANESE_ORCHID, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.JAPANESE_ORCHID.getRegistryName()),
                FlowerItems.KOVAN_FLOWER = new BlockItem(FlowerBlocks.KOVAN_FLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.KOVAN_FLOWER.getRegistryName()),
                FlowerItems.LAZARUS_BELLFLOWER = new BlockItem(FlowerBlocks.LAZARUS_BELLFLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.LAZARUS_BELLFLOWER.getRegistryName()),
                FlowerItems.LOLIPOP_FLOWER = new BlockItem(FlowerBlocks.LOLIPOP_FLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.LOLIPOP_FLOWER.getRegistryName()),
                FlowerItems.MAGENTA_TULIP = new BlockItem(FlowerBlocks.MAGENTA_TULIP, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.MAGENTA_TULIP.getRegistryName()),
                FlowerItems.ORANGE_DAISY = new BlockItem(FlowerBlocks.ORANGE_DAISY, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.ORANGE_DAISY.getRegistryName()),
                FlowerItems.ORSIRIA_ROSE = new BlockItem(FlowerBlocks.ORSIRIA_ROSE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.ORSIRIA_ROSE.getRegistryName()),
                FlowerItems.PEACH_LEATHER_FLOWER = new BlockItem(FlowerBlocks.PEACH_LEATHER_FLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PEACH_LEATHER_FLOWER.getRegistryName()),
                FlowerItems.PINK_ALLIUM = new BlockItem(FlowerBlocks.PINK_ALLIUM, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PINK_ALLIUM.getRegistryName()),
                FlowerItems.PINK_ANEMONE = new BlockItem(FlowerBlocks.PINK_ANEMONE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PINK_ANEMONE.getRegistryName()),
                FlowerItems.PINK_DAFFODIL = new BlockItem(FlowerBlocks.PINK_DAFFODIL, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PINK_DAFFODIL.getRegistryName()),
                FlowerItems.PINK_ORCHID = new BlockItem(FlowerBlocks.PINK_ORCHID, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PINK_ORCHID.getRegistryName()),
                FlowerItems.PROTEA_FLOWER = new BlockItem(FlowerBlocks.PROTEA_FLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PROTEA_FLOWER.getRegistryName()),
                FlowerItems.PURPLE_ORCHID = new BlockItem(FlowerBlocks.PURPLE_ORCHID, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PURPLE_ORCHID.getRegistryName()),
                FlowerItems.PURPLE_SAGE = new BlockItem(FlowerBlocks.PURPLE_SAGE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PURPLE_SAGE.getRegistryName()),
                FlowerItems.PURPLE_TULIP = new BlockItem(FlowerBlocks.PURPLE_TULIP, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PURPLE_TULIP.getRegistryName()),
                FlowerItems.RED_CORNFLOWER = new BlockItem(FlowerBlocks.RED_CORNFLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.RED_CORNFLOWER.getRegistryName()),
                FlowerItems.RED_ORCHID = new BlockItem(FlowerBlocks.RED_ORCHID, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.RED_ORCHID.getRegistryName()),
                FlowerItems.RICHEA = new BlockItem(FlowerBlocks.RICHEA, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.RICHEA.getRegistryName()),
                FlowerItems.ROSE = new BlockItem(FlowerBlocks.ROSE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.ROSE.getRegistryName()),
                FlowerItems.SILVER_VASE_FLOWER = new BlockItem(FlowerBlocks.SILVER_VASE_FLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.SILVER_VASE_FLOWER.getRegistryName()),
                FlowerItems.SNOWDROPS = new BlockItem(FlowerBlocks.SNOWDROPS, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.SNOWDROPS.getRegistryName()),
                FlowerItems.TORCH_GINGER = new BlockItem(FlowerBlocks.TORCH_GINGER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.TORCH_GINGER.getRegistryName()),
                FlowerItems.VIOLET_LEATHER_FLOWER = new BlockItem(FlowerBlocks.VIOLET_LEATHER_FLOWER, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.VIOLET_LEATHER_FLOWER.getRegistryName()),
                FlowerItems.WHITE_ANEMONE = new BlockItem(FlowerBlocks.WHITE_ANEMONE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.WHITE_ANEMONE.getRegistryName()),
                FlowerItems.WHITE_SAGE = new BlockItem(FlowerBlocks.WHITE_SAGE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.WHITE_SAGE.getRegistryName()),
                FlowerItems.WINTER_CYCLAMEN = new BlockItem(FlowerBlocks.WINTER_CYCLAMEN, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.WINTER_CYCLAMEN.getRegistryName()),
                FlowerItems.WINTER_ROSE = new BlockItem(FlowerBlocks.WINTER_ROSE, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.WINTER_ROSE.getRegistryName()),
                FlowerItems.WINTER_SCILLA = new BlockItem(FlowerBlocks.WINTER_SCILLA, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.WINTER_SCILLA.getRegistryName()),
                FlowerItems.YELLOW_DAFFODIL = new BlockItem(FlowerBlocks.YELLOW_DAFFODIL, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.YELLOW_DAFFODIL.getRegistryName()),
                FlowerItems.YELLOW_TULIP = new BlockItem(FlowerBlocks.YELLOW_TULIP, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.YELLOW_TULIP.getRegistryName()),
                FlowerItems.AMARANTH = new BlockItem(FlowerBlocks.AMARANTH, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.AMARANTH.getRegistryName()),
                FlowerItems.CYAN_AMARANTH = new BlockItem(FlowerBlocks.CYAN_AMARANTH, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.CYAN_AMARANTH.getRegistryName()),
                FlowerItems.ORANGE_AMARANTH = new BlockItem(FlowerBlocks.ORANGE_AMARANTH, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.ORANGE_AMARANTH.getRegistryName()),
                FlowerItems.MAGENTA_AMARANTH = new BlockItem(FlowerBlocks.MAGENTA_AMARANTH, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.MAGENTA_AMARANTH.getRegistryName()),
                FlowerItems.PURPLE_AMARANTH = new BlockItem(FlowerBlocks.PURPLE_AMARANTH, new Item.Properties().group(ItemGroup.DECORATIONS)).setRegistryName(FlowerBlocks.PURPLE_AMARANTH.getRegistryName())

                        //


                        );
    }

    private static ResourceLocation location(String name) {
        return new ResourceLocation(BYG.MODID, name);
    }
}
}

