package sporeaoc.byg.block;

import net.minecraft.block.Block;

public class FlowerBlocks {
    public static Block ALPINE_BELLFLOWER;
    public static Block ALLIUM_FLOWER_BUSH;
    public static Block PINK_ALLIUM_FLOWER_BUSH;
    public static Block ANGELICA;
    public static Block AZALEA;
    public static Block BEGONIA;
    public static Block BISTORT;
    public static Block BLACK_ROSE;
    public static Block BLUE_SAGE;
    public static Block CALIFORNIA_POPPY;
    public static Block CROCUS;
    public static Block CYAN_ROSE;
    public static Block CYAN_TULIP;
    public static Block DAFFODIL;
    public static Block DELPHINIUM;
    public static Block FAIRY_SLIPPER;
    public static Block FIRECRACKER_FLOWER_BUSH;
    public static Block FOXGLOVE;
    public static Block GOLDEN_SPINED_CACTUS;
    public static Block GREEN_TULIP;
    public static Block GUZMANIA;
    public static Block INCAN_LILY;
    public static Block IRIS;
    public static Block JAPANESE_ORCHID;
    public static Block KOVAN_FLOWER;
    public static Block LAZARUS_BELLFLOWER;
    public static Block LOLIPOP_FLOWER;
    public static Block MAGENTA_TULIP;
    public static Block ORANGE_DAISY;
    public static Block ORSIRIA_ROSE;
    public static Block PEACH_LEATHER_FLOWER;
    public static Block PINK_ALLIUM;
    public static Block PINK_ANEMONE;
    public static Block PINK_DAFFODIL;
    public static Block PINK_ORCHID;
    public static Block PROTEA_FLOWER;
    public static Block PURPLE_ORCHID;
    public static Block PURPLE_SAGE;
    public static Block PURPLE_TULIP;
    public static Block RED_CORNFLOWER;
    public static Block RED_ORCHID;
    public static Block RICHEA;
    public static Block ROSE;
    public static Block SILVER_VASE_FLOWER;
    public static Block SNOWDROPS;
    public static Block TORCH_GINGER;
    public static Block VIOLET_LEATHER_FLOWER;
    public static Block WHITE_ANEMONE;
    public static Block WHITE_SAGE;
    public static Block WINTER_CYCLAMEN;
    public static Block WINTER_ROSE;
    public static Block WINTER_SCILLA;
    public static Block YELLOW_DAFFODIL;
    public static Block YELLOW_TULIP;
    public static Block AMARANTH;
    public static Block CYAN_AMARANTH;
    public static Block ORANGE_AMARANTH;
    public static Block MAGENTA_AMARANTH;
    public static Block PURPLE_AMARANTH;

}
